### ISSUE TITLE
Better call to donate at results page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#10]
When people receive the results they want, they should be reminded to support the project by donating or joining.

**Comment by graphiclunarkid** [comment]
Could we use one of @webal's CTA side-bar elements for this ( openrightsgroup/blocked-org-uk#48 )?

**Comment by JimKillock** [comment]
I expect that would work!

**Comment by webal** [comment]
I'll add one on

**Comment by graphiclunarkid** [comment]
I've done this in text for now since the space on this page doesn't lend itself well to using @webal's CTA chunk right now. We can come back to this later and make it more pretty if we like though!
