### ISSUE TITLE
URL change to permalink on a per check basis

### ISSUE THREAD

**Issue by lewiscowper** [openrightsgroup/cmp-issues#100]
Instead of directing users to the /thankyou page after a check it might be helpful to have the link become the permalink to the check specifically. This might be way more difficult than I anticipate, but if not you also might wind up being able to cache frequently checked sites and it could open things up like that.

**Comment by dantheta** [comment]
Another benefit of this would be to be able to point people at a historical blocked result, even if the site has been subsequently unblocked.  The database preserves the results of all historical checks, although there is no frontend for it currently.
