### ISSUE TITLE
Number of pending tests is huge

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#101]
The front-page statistics currently claim there are 1998060 pending tests. This seems unlikely!

![screenshot from 2014-11-19 17 58 32](https://cloud.githubusercontent.com/assets/433456/5110071/f41f065c-7015-11e4-9c8e-a81c710af359.png)

**Comment by dantheta** [comment]
That's the DMOZ import - I'm moving those off to a separate table in order to introduce them to the system more gradually.

**Comment by dantheta** [comment]
Fixed that.  When the disk space expansion is done, we'll import the dmoz urls into a holding table and introduce them gradually.
