### ISSUE TITLE
Test citizenlab URL lists using Blocked

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#102]
The lists at https://github.com/citizenlab/test-lists seem to try to walk lines of controversy so that censorship can be profiled. We should import at least the global list for testing.

I notice there doesn't seem to be a UK list. Perhaps we can compile one from our results and contribute it back?

This dataset could be particularly useful for trying to detect the level of filtering active on a line (if the listed sites are marginal cases for an "adult content" filter).

**Comment by dantheta** [comment]
An importer for the citizenlab test sets has been added to the feature/unicode_urls branch.
