### ISSUE TITLE
Ajax results don't populate if row doesn't exist already

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#103]
I am testing a new site that has no previous results. The results page loads and the results table contains rows for each ISP where results were returned quickly enough.

No new rows are added to this table - regardless of how long I wait - however if I refresh the page more rows are displayed. The contents of these rows are then updated via AJAX calls.

I would expect new rows to be displayed when slower results arrive even if this is the first time I have checked this URL.

**Comment by Stubbs** [comment]
Which repo is this for @graphiclunarkid ?

**Comment by graphiclunarkid** [comment]
I think it was developed against the example client in blocking-middleware. See #25 for the discussion & link to pull request.

Unfortunately we've not yet found a way to expose on github the PHP code that runs the front-end. That's because our CMS, Modx, stores all its code in a MySQL database rather than the file-system.

I keep trying to figure out how to use git with Modx so that we can release all the front-end code here - however I haven't got very far yet :frowning:

**Comment by Polarisation** [comment]
This should be fixed when we update the js on the live site (see #25)
