### ISSUE TITLE
Record blocks that occur due to malware

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#108]
Some services, such as Virgin Net, will block sites as a result of being listed as sources of malware.

The probe should regard these as blocked but in a separate category from Parental/Court/CAIC.

e.g. https://www.blocked.org.uk/results?url=http://www.extraordinaryrendition.org
should be detected as blocked on Virgin due to http://assets.virginmedia.com/malware.html being returned.

(Will require a corresponding front-end change to display cause.)

**Comment by dantheta** [comment]
Fixed - https://www.blocked.org.uk/results?url=http://www.extraordinaryrendition.org is now reported as "blocked" on virginmedia.  The database records that the blocktype is "MALWARE", as opposed to "parental" or "copyright".

**Comment by dantheta** [comment]
Sorry, commented against the wrong issue.  Should have been #120.
