### ISSUE TITLE
Results page caching prevents AJAX updates

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#109]
@gwire performed some magic at the ORGCon hack-day to suppress the caching of the results page so that the AJAX live-results update worked smoothly. This seems to have regressed. Probably my fault - sorry!

See discussion in openrightsgroup/Blocking-Middleware#60

If we could document how to prevent future regression that would be really handy.

**Comment by gwire** [comment]
After trying a bunch of different things, in the end I believe it worked after I modified the APIHelper snippet to add a line after "Connection: close".

```
header("Connection: close");
while (@ob_end_clean());
```

Added back on the live site.

**Comment by graphiclunarkid** [comment]
Thanks @gwire!

P.S. I have realised that Github comment URLs are a never-ending source of previously-unchecked URLs for testing Blocked :wink:
