### ISSUE TITLE
Data licence

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#11]
The data needs a licence. We're happy with permissive but it should definitely have a strong attribution element. Note: we think we should avoid making the service "commercial" as such as we are a public interest organisation and we are providing the data in the public interest.

**Comment by graphiclunarkid** [comment]
I have proposed:
- CC-BY-SA for site content (matches org.org, though I've used the new v4.0 international rather than v3.0 unported)
- MIT or GPLv3 for software
- CC-BY-NC-SA for data (same as org.org, but non-commercial, as requested).
