### ISSUE TITLE
Rate-limiting target URL tests is now live - do we need to update the thankyou page text?

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/cmp-issues#111]
We now have rate-limiting code which ensures that a target URL is only tested once in a 24-hour period, even if multiple people request a check.

If a target URL has already been checked, the results page shows the most recent set of results (which are <24 hours old at this point).

The wording on the page says:

"The URL you submitted is now being checked for filtering by our probes." - while this is mostly true, do we need to update the text to explain why the results might be up to 24hours old?

**Comment by graphiclunarkid** [comment]
Yes, I think we do. We should also add a FAQ entry. And I also think #105 might now be slightly more important to implement too.

**Comment by dantheta** [comment]
This is taken care of in the new frontend.
