### ISSUE TITLE
Integrate category and location data-browsers into web front-end

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#113]
We now have an amazing facility to drill down through DMOZ category data to identify blocked sites (see #76). It's available temporarily here:

http://api.blocked.org.uk:5000/

The next step is to integrate this with the web front-end for visitors to use.

**Comment by graphiclunarkid** [comment]
We also now have importers for MP / PPC (#115, openrightsgroup/Blocking-Middleware#63) and charity (#82, openrightsgroup/Blocking-Middleware#64) websites to integrate.

**Comment by webal** [comment]
Before we do this it makes sense to sort out a more flexible way of tagging data from multiple sources, see this issue https://github.com/openrightsgroup/cmp-issues/issues/119 for discussion on that.

**Comment by graphiclunarkid** [comment]
I was thinking that life might be simpler (and the data might be more navigable) if we were to separate the "browse by location" from the "browse by category" features. The same information would be displayed in both trees - but they would have separate roots and branches.

**Comment by dantheta** [comment]
The DMOZ category API functions have now been added, tested and released.  The API documentation has also been updated to add the two new functions.
