### ISSUE TITLE
Pre-check URL characteristics before queueing them for real testing

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#114]
There may be good reasons to preprocess URLs before forwarding them to ISP queues for checking. These include
- Do we really want to check images, shockwave flash files, and other non text/\* mime types?
- Can we make censorship testing more robust by comparison with results from a known clean connection?

Drawing together discussion from: openrightsgroup/Blocking-Middleware#45, openrightsgroup/Blocking-Middleware#46, #107

**Comment by dantheta** [comment]
Pre-checking of robots.txt, content-type and content-length is live.  May require a few refinements over time.

**Comment by graphiclunarkid** [comment]
I think we should close this now. We have a queue implemented for pre-checking URLs and we can add checks as we discover the need for them.
