### ISSUE TITLE
Push blocked-URLs list to CensorSweeper

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#116]
This tool censorsweeper.com was designed to
check a lot of sites in parallel and present it dramatically.

the code is here:

https://github.com/kubla/censorsweeper

we could fork it and put all the uk sites we've found blocked in so people can check their connection:

https://github.com/kubla/censorsweeper/blob/master/js/sitelist.js

**Comment by edjw** [comment]
That site doesn't run any more so I'm closing this
