### ISSUE TITLE
Automated database-backup

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#117]
Our backup strategy is ad-hoc at the moment. We should automate it.

**Comment by graphiclunarkid** [comment]
What size is the database currently and how quickly does it grow (excluding us dumping in datasets directly via the API)?

**Comment by dantheta** [comment]
Compressed, it's 250MB.  I'll keep an eye on the growth rate.  The DMOZ import added 60% overnight!

I've set up duplicity to archive to a rmtbkp user on ooni-1.

It will backup relevant filesystem locations and a daily full dump of the database.  Duplicity will manage expiry.

I'll add the gory details to the config repo.

**Comment by graphiclunarkid** [comment]
Thanks for arranging this - I feel a bit safer knowing we have at least one backup (even though I know you were doing some too)!

In the new year we'll be rebuilding ooni-1 to reduce its disk space (it has a lot spare), so if we do that we will need to reconfigure these backups too, as it will involve nuking the existing VM in favour of a new one. We could take that opportunity to shift these over to a "production" backup server (there are people with access to ooni-1 who haven't signed ORG's confidentiality agreement).
