### ISSUE TITLE
Better tagging of sources

### ISSUE THREAD

**Issue by webal** [openrightsgroup/cmp-issues#119]
Now we're getting data from multiple sources there's going to be a need to pull out data based on the source and any information that comes with the source. Currently the database allows for one source only, and there's going to be overlap meaning that this information is lost.

For example, imagine that we have an MPs site that is Dmoz and has already been imported, the source in the urls table is set to dmoz and the dmoz categories are saved in a separate table. Now that the MP data is ready to be imported many of the same urls are going to be imported, but currently it skips adding a url that is already in there. This means that when we query the database to pull out MPs sites it only returns those that were not already present because of adding through the site or imported via dmoz.

I guess it makes sense to have a separate sources table to allow a url to have multiple sources.

 Also as many sources contain extra data - geographic locations in the case of a large chunk of dmoz and all the MP data I wonder if there's any merit to having a standardised way of adding this data so when do a geographic query it uses the location from whatever source is available.

**Comment by webal** [comment]
I was thinking of adding a sources table with the following columns:

urlID
source
country
county
town
site_type

Most of the datafeeds we've used have town/county and this should be easy to populate with. We could also extract this info from dmoz. Obviously this would only be for UK sites, but then there's probably no real need for sorting data from other countries??

The site type could be used across different sources, eg Mps data would be 'political' and open charities would be marked as charities. It would also allow us to do some basic tagging of the dmoz data as we can identify some charities, businesses, political sites as such from the category hierachy. This would give us several useful top level categories to sort the data by.

I think with this in place we could create something similar to Dan's Dmoz browser where you can filter down by location or website type. as regquested here: https://github.com/openrightsgroup/cmp-issues/issues/113

I's like to know whether people think this is a good approach, or if there's any other data we should be adding - we do have names of MPS/charities/etc but I'm not sure how much practical use that would be

**Comment by graphiclunarkid** [comment]
We need to keep in mind the possibility of handling sites from other countries. Not only will those end up in our database anyway, but also ORG is in discussions about potentially deploying Blocked abroad, so we shouldn't preclude anything at this stage :smile: If it's just a matter of not having the data then I think that's ok though.

By "site type" did you mean DMOZ category, and by "source" did you mean MyNextMP, open charities etc?

I will comment over on #113 about how I thought browsing down through the data could work.

One thing we could consider is keeping a separate "locations" table. I think sites from multiple different sources could be in the same location, for example.

**Comment by webal** [comment]
It's easy enough to add in the country data (amended original post)

Source - yes basically the datafeed/source we got the data from - dmoz/open charities/etc

Site type - would have to be fairly basic, I was imagining using the same categorization as we have on the blocked site ie business/charity/government/etc

The way suggested above would save the location/categorization as determined by the source that was used. This way if they differed it would appear in all cats/locations, rather than having one location stored per URL where it would be harder to resolve any conflicts about which source is more reliable. That said there's nothing stopping us storing the location data in a separate table.

**Comment by dantheta** [comment]
I was thinking that we could generalise this further.  If we extend the database to store arbitrary key/value pairs against each URL, then we can represent set membership and other extended attributes based on the source/import method.  Although an EAV storage pattern isn't the most optimal way of storing data in an RDBMS, it is extremely flexible.  

We wouldn't have to create an array of additional tables for NextMP, OpenCharities or DMOZ, but could instead store the data for each inside the generalised table.  It lends itself well to exposure through the JSON api as well.

**Comment by webal** [comment]
would that be for geographic data as well?

**Comment by dantheta** [comment]
We could contain both in the same table.  For example, if we've got a charity website with urlID 1001, then we could store the following attributes:

| urlID | Attribute | Value |
| --- | --- | --- |
| 1001 | Set:OpenCharities | 1 |
| 1001 | Set:DMOZ | 1 |
| 1001 | Dmoz:Category | Regional/UK/East_of_England/Charities |
| 1001 | Addr:Town | Colchester |
| 1001 | Addr:Postcode | CO10 0AA |

We can codify the attributes and namespaces however we like.  Querying through SQL works reasonably well (although it gets more complicated as you add more criteria to the query).

**Comment by webal** [comment]
sounds good, how would that work with a hierachy, eg if you wanted to browse all the blocked sites in a county then narrow that down to a town within a county?

**Comment by dantheta** [comment]
We probably wouldn't build a postal address hierarchy directly, but we can reasonably easily run a query to find the values of the Addr:Town attribute on all urls that have Addr:County == Essex.  Those towns could be presented in the frontend.  Once the user had selected one, the system runs a query for urls that have Addr:County == Essex and Addr:Town = [Selection].

Representing those hierarchically would fall to the frontend, rather than anything baked into the data model.  The frontend would know that towns occur inside counties, so to do a "drill-down", it should show counties as the more general level and then show towns inside them.

Hope that makes sense!

**Comment by webal** [comment]
I've had a stab at getting the data in, you can see the branch here: https://github.com/openrightsgroup/Blocking-Middleware/tree/generic_tags/backend. I've noticed a few issues that's probably worth having a think about before it goes much further:
1. To prevent duplicate tags being entered on every import of data I've added an extra fields to what Dan suggested for the tags - the source of the tag, whilst it's a lot of redundant data it does allow me to wipe previous records for that url and source combination. THere may be a neater way of doing this - let me know if you can think of one!
2. I've left an attribute in for the source, given that we're saving the source with each tag it might be redundant - but I thought it might make handled the data more consistent when it comes to pulling the data out - I'm open to suggestions for removing/keeping this.
3. The only geo data in the MP  data is the constituency, I've added this under MP:const. I would have liked to have linked this into county/towns - is there a data source I can do this from?
4. The charity data contains the address data in a single field, some address have the county listed others don't. My original plan was to take penultimate element of the address as the county and the 3rd from last as town but this won't work. We do have the postcode, and we could ping Google to get address data from Google, but they may take exception to 300000 odd calls! Is there another way, or does anyone have experience doing this?
5. I think I've seen that the MP API allows you to get a constituency from a postcode (and possibly town/county??), if so it may be feasible to attach a constituency to each url which would be ideal for the campaigning you've got planned. ALthough if you can get a dump we can keep in a db this would be a lot quicker than several thousands calls to an external API.
6. In the UK dmoz sorts its regional data like this: UK > England > Kent > Canterbury. I was planning to omit England/Scotland/Wales/NI as people will know where it is based on the county, any objections? For all other countries I'll only save the country, there's quite a bit of regional variation and it'll be a bit trickier in other countries.

If anyone wants to give the code a test run then just checkout that branch, I've only run it against a few small sets of data.

**Comment by dantheta** [comment]
Hiya - 

Yep, that's the sort of thing I was thinking of, although I'd also been wondering about refactoring some of the import scripts that we're adding so that they use the service objects from the API instead of repeating common insert queries.  Inserting a URL is pretty common, so the import scripts could use the UrlLoader object from api/1.2/libs/services.php.  The UrlLoader would also be a pretty good place to house the tag manipulation functions as well, rather than having them on the DB class.  
1.  I'm not 100% sure about the extra origin field on the tag records.  A simpler approach might be to uniquely index tags so that a URL can only have 1 occurrence of a given tag, and have the library functions manipulate them using a "REPLACE INTO" SQL statement, rather than transactionally removing them.   
2. I think the set membership information is still important to retain, but if we're uniquely indexing the tags then we need to represent the sources slightly differently - that's the set:<setname> examples that I was thinking of.
3. I think if the origin data has only got constituency, then we can't add more detailed information than that.  
4. Yep, I've done address formatting like this.  Extracting the postcode is reliable, and from there perform a postcode info lookup (http://uk-postcodes.com/postcode/NR31PD.json, OS Opendata license) can give you well-formed county and town data.  The first line or two of the address can be retained for building name/number and street name information.
5.  I've still got to do a little bit of work on the DMOz data in the live database -  there were a few character set issues during the import, so some of the categories that should exist are missing.

**Comment by webal** [comment]
I was thinking the same about adding a couple of sandard methods for adding URLs to, I did it for the tags, certainly worth expanding. Did you wan to have a crack at that? If not I can have a go next week.
1. The reason for allowing the same tag from different sources would be in case there were discrepancies between different sources it would been it always had the correct tag (and also an incorrect one!). If you think this isn't an issue it's easy enough to remove.
2. I've not used key indexes much so if it's easier to use set:dmoz = 1 rather than set=dmoz then I'll swap this over.

4 . Do you know of a downloadable copy of the address data? Would prefer that than 300,000 http requests if possible.

6 . I'll leave dmoz for a bit util that's sorted

also the numbering seems to get messed up in github - it makes them all sequential :/

**Comment by webal** [comment]
Also regarding point 1, how will we handle removing obsolete tags if we use replace into?

**Comment by dantheta** [comment]
For (1), I think we can see how it goes.  We can include a source on the tag and not uniquely index to start with, and see if the data winds up tidy enough without imposing more rules on it.  

I'm about to commit some changes which put the tag maniplation functions on the UrlLoader class, and also make use of that class in the MP importer.  

I don't know of a downloadable version of that address data.  There are a couple of library toolkits in a variety of languages which take care of rate limiting, caching and de-duplicating, which at least mean that the consumer of the data can feel reasonably comfortable making large numbers of calls to it - it's obviously intended usage.

I noticed that about github's numbering too ...

**Comment by edjw** [comment]
Can we close this @dantheta?

**Comment by dantheta** [comment]
I think so - we didn't go as far as importing rich structured data relating to a URL, but we do have more flexible set membership information (allowing a URL to belong to multiple source collections) which achieves some of the same things.  We've also massively scaled up the number of URLs in the system, so curating structured data for collections of URLs becomes quite a bit more taxing.  Hope that's OK, webal.
