### ISSUE TITLE
Errors caused by large DNS responses?

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#121]
A check of https://www.blocked.org.uk/results?url=http://www.yify-torrents.com shows a number of "dnserror" responses, where I would expect "blocked" for BT/Sky/TalkTalk/Virgin.

Is this related to the size of the response being larger than UDP packet limits and therefore requiring TCP?  Are these actual DNS errors, or could there be an issue with the probes dropping oversized DNS responses?

**Comment by dantheta** [comment]
I don't think it's the large DNS response that cause the problem - a retest with no configuration change tested the site successfully.  The responses in the logs suggest a transient nameserver or zone problem.

Hope that's OK.
