### ISSUE TITLE
API endpoint to generate oonideckgen URL list from our database

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#123]
This issue is part of epic #78

OONI now have a tool that is shipped as part of ooniprobe called oonideckgen. This generates a test deck of URLs to be used by ooni-probe depending on the country in which it is running (determined by GeoIP lookup).

The URLs to test come from the [CitizenLab corpus](https://github.com/citizenlab/test-lists), which seems to have derived them manually, on the advice of experts in each country. There is no current CitizenLab corpus for the UK.

We have a separate issue for testing the CitizenLab URLs using Blocked (#102).

This issue is to expose a Blocking-Middleware API endpoint that returns a list of URLs to test for the UK that oonideckgen can use.

We could consider specialising this to the network on which the probe is running. Alternatively it might be useful to test the same list regardless of network so that we can compare results. A combination of both is possible by concatenating global and per-network sets into a single list.

**Comment by dantheta** [comment]
This has been completed, and will be added to a branch very soon.  It features client network detection (so that a separate call is not required to identify the client network), and authenticates using the normal probe credentials.

**Comment by dantheta** [comment]
This approach has been superceded by the ORG queue integration into ooni-probe.  The oonideckgen approach was also a little limited, in that oonideckgen expects URL lists from a fixed location to have fixed content (they are identified by hash-of-contents in the caching layer); IIRC, the caching layer would have to be disabled to allow a URL list to be refetched with different content.
