### ISSUE TITLE
EPIC: accept results from non-ORG probes

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#124]
We want to allow people to run their own probes and send us their results. There are a few challenges to overcome:
- How can we sure about the level of filtering that is applied to the connection being tested if we haven't configured it ourselves?
- Users who are not using their ISP's DNS servers (e.g. using 8.8.8.8 instead), or are using a VPN, or Tor etc. might circumvent censorship.
- Few people who would contribute results want their lines to be filtered.

**Comment by dantheta** [comment]
There are also issues surrounding informed consent - in higher-stakes territories, running software that makes HTTP requests to URLs read from a remote source  can carry quite series legal and personal risks.

**Comment by edjw** [comment]
This is done because we provide probes now. Closing
