### ISSUE TITLE
Store the Pin SHA256 fingerprint when checking HTTPS URLs

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#131]
For https URLs being queried it would be good if we could store the SHA26 Pin fingerprint for the certificate of the connection at the point it was checked (i.e. the format used by [RFC 7469](https://tools.ietf.org/html/rfc7469) key pinning).

e.g. the current cert pin-sha256 for www.blocked.org.uk would be `FxH/anX7NVkY0MbnFwOkUBvrK6xjhRAQAh3ZrWDG7uo=`

We could then output this in the API - and surface in the frontend when there are different certs used for different tests (which is not in itself necessarily an issue - some sites have multiple certs, certs get swapped out, etc)

``` bash
$ openssl s_client -servername www.blocked.org.uk -connect www.blocked.org.uk:443 \
  </dev/null 2>/dev/null| openssl x509 -pubkey -noout | openssl rsa -pubin -outform \
  der  2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64 
FxH/anX7NVkY0MbnFwOkUBvrK6xjhRAQAh3ZrWDG7uo=
```

**Comment by dantheta** [comment]
SSL fingerprints are being stored now.  They aren't visible from the frontend, but we can forward any anomalous URLs to ooni for more comprehensive testing.
