### ISSUE TITLE
Software licenses

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#15]
Each repository needs to have a LICENSE file. These should be Free Software licenses allowing reuse with attribution. It would be great if we could get everyone to agree on a single license across all repositories so that people don't have to navigate a licensing minefield if they want to reuse more than one component.

My suggestion would be GPLv3.

**Comment by webal** [comment]
I'm fine with that

**Comment by dantheta** [comment]
I think the middleware started out as gplv2, but I'm happy with that if everyone else is.

**Comment by graphiclunarkid** [comment]
We could use GPLv2 if there were some merit to using that version. It allows "either version 2 of the License, or (at your option) any later version."

Wondering what @NetworksAreMadeOfString, @anadahz, @korikisulda, @mkillock and @liamja think?

**Comment by NetworksAreMadeOfString** [comment]
The original commit of the middleware is/was GPL 2 or 3.

I expect some of the 1.1 files might have comment headers to that effect.

**Comment by dantheta** [comment]
We've used Silex as well, which is currently bundled with Blocking-Middleware.  The AMQP driver is php-amqp from pecl, available under the PHP license.

**Comment by graphiclunarkid** [comment]
All repositories are now licensed as follows:
- GPLv3 (or MIT where that was already the case) for code
- CC-BY-SA 4.0 international for content

**Comment by webal** [comment]
bit late to the party, but front end wise we're using:

jquery, (MIT) : https://jquery.org/license/
Social share icons (MIT): https://github.com/panzi/SocialSharePrivacy/
Circles.js (MIT): https://github.com/lugolabs/circles
Modernizr MIT & BSD
Lato font (from google fonts) Licensed under the SIL Open Font License
REM polyfill MIT: https://github.com/chuckcarpenter/REM-unit-polyfill

**Comment by graphiclunarkid** [comment]
Thanks @webal. I'll update the README and the license page when I get a minute.
