### ISSUE TITLE
Extract and store open graph meta information from sites

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#154]
Extract and save particular meta information for sites. e.g. [Open Graph](http://ogp.me) and [Twitter Cards](https://dev.twitter.com/cards/markup) and make it available from the API.

e.g.
`<meta name="twitter:site" content="@OpenRightsGroup">`

This would mean that if www.openrightsgroup.org gets blocked, the frontend might, for example, provide the ability to tweet a site owner to inform them of the block.

**Comment by dantheta** [comment]
Applicable data now being collected in site_description table.
