### ISSUE TITLE
Session cookie domain being set incorrectly by MODX

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#16]
The new blocked.org.uk context setting session_cookie_domain does not seem to be overriding the system setting (of .openrightsgroup.org ) 

curl -v https://new.blocked.org.uk > /dev/null shows the incorrect cookie being sent.

**Comment by JimKillock** [comment]
@gwire notes: session_cookie_domain is not working for this sub site. Please continue to investigate, and raise a bug with ModX developers.
Varnish workaround is to intercept pages coming from the backend, checking for the cookie domain is ".openrightgroup.org" and rewriting it to ".blocked.org.uk". This is a short term monkey-patch - not a real fix.
While this issue is being looked at, uou'll be able to check if the rewrite activated as it will preserve the original cookie in a "X-Set-Cookie-Orig" header.

@gwire added
Also note that the Varnish config patch, if still needed, will need to be updated at "go live" as it only checks on requests for new.report.org.uk

**Comment by JimKillock** [comment]
I've tested this on my own install, and the settings work ok. Next steps might be to try on stage.blocked.org.uk (add a domain stage2.blocked.org.uk perhaps) or on ORG staging to see if we can replicate the error.

**Comment by JimKillock** [comment]
OK, we have an answer from the MODX devs: 

http://forums.modx.com/thread/91099/session-cookie-setting-not-doing-anything#dis-post-498884

"The problem is that gateway manager is a plugin and has to switch to a context, but the session is always loaded by the default context loaded in the index.php (web). In order to use a different session for your subdomain, you would need to modify the index.php and have it handle the initialization of the correct subdomain context in the first place."

So it looks like we have to either rewrite index.php or not use Gateway Manager (which was a recent switch in any case).

**Comment by JimKillock** [comment]
@mkillock Can I hand this to you?

**Comment by mkillock** [comment]
umm, bit mystified by what Mr Coward means tbh. Presumably you can't remove Gateway Manager because you wont be able to host multiple domains on the same MODx instance?

http://rtfm.modx.com/extras/revo/gatewaymanager

**Comment by JimKillock** [comment]
So we were using individual site handlers, rather than GatewayManager. But both those, and GatewayManager reply on a system event, that takes place after index.php runs, so yes it does seem a little less clear than I thought.

**Comment by mkillock** [comment]
My best guess at what he means by editing index.php is to look at the requested domain and set the context in index.php before GatewayManager is called - is that your understanding?

**Comment by mkillock** [comment]
presumably cookies are set for various domains in ORG's MODx instance? If so then we need to perhaps have some code to match requested domain to session context

**Comment by mkillock** [comment]
OK, in index.php, there is this section:

/\* Initialize the default 'web' context */
$modx->initialize('web');

So perhaps replace it with something like (untested)

$requestdomain = strtolower ($_SERVER['SERVER_NAME']);
//switch context for blocked.org.uk to make cookies work properly
if ($requestdomain == 'new.blocked.org.uk') {
  $modx->initialize('new.blocked.org.uk');
  }  
else {
  //use default context for everything else
  $modx->initialize('web');
  }

**Comment by mkillock** [comment]
we'd need to test this on staging first

**Comment by JimKillock** [comment]
Yes, I think this is right. And definitely needs testing first!

**Comment by JimKillock** [comment]
Maybe also worth replying on that thread to Opengeek?

**Comment by mkillock** [comment]
ok have done

**Comment by graphiclunarkid** [comment]
(Just a note that this was split out from openrightsgroup/blocked-org-uk#44 into its own issue and that openrightsgroup/blocked-org-uk#44 depends on this being resolved).

**Comment by graphiclunarkid** [comment]
Hi @mkillock, @jimkillock - are you still working on this bug or did the patch introduced by Matt fix the issue?

**Comment by mkillock** [comment]
Looks like the suggested way of doing this is:

<?php
/\* don't execute if in the Manager */
if ($modx->context->get('key') == 'mgr') {
        return;
}

switch ($_SERVER['HTTP_HOST']) {
        case 'domain2.tld':
                // if the http_host is of a specific domain, switch the context
                $modx->switchContext('domain2.tld');
                break;
        case 'domain3.tld':
                // if the http_host is of a specific domain, switch the context
                $modx->switchContext('domain3.tld');
                break;
        default:
                // by default, don't do anything
                break;
}
?>

I haven't changed anything yet - but things are still working, presumably because of the varnish hack

**Comment by graphiclunarkid** [comment]
Hmm, ok. Maybe you and @gwire could find a time to reverse that hack and try out the suggested solution? We can always put it back again if this doesn't work!

**Comment by mkillock** [comment]
I need shell access to the ORG main server, or otherwise @gwire will need to edit the index.php file for us, with the following (untested)

<?php
/\* don't execute if in the Manager */
if ($modx->context->get('key') == 'mgr') {
return;
}

$requestdomain = strtolower ($_SERVER['SERVER_NAME']);
switch ($requestdomain) {
case 'new.blocked.org.uk':
// if the http_host is of a specific domain, switch the context
$modx->switchContext('new.blocked.org.uk');
break;
default:
// by default, don't do anything
break;
}

?>

**Comment by mkillock** [comment]
Or I can test on staging, and ask for it to be copied over? Can't really test it entirely on staging though (only one context at the moment), and also there is a risk of breaking everything on live because it requires changes to index.html.

Advice please!

**Comment by graphiclunarkid** [comment]
Needs review by @gwire. Have emailed to ask.

**Comment by graphiclunarkid** [comment]
@gwire has very kindly switched the varnish hack over to www.blocked.org.uk. In the middle of the night. At no notice. Thanks!

He mentioned that we need to make the cookie HTTPS only, but that won’t break the site ATM, so just needs to go on the to-do list.

**Comment by gwire** [comment]
It's the root index.php and I am _loathe_ to maintain patches for upstream ModX code - that would almost certainly bite us on some future upgrade. I'm sticking with the Varnish magic for now.

Next related step is: 
- ensure only https support on the live site
- set HSTS header
- rewrite outgoing cookie to "secure only"

**Comment by gwire** [comment]
- All requests to http://blocked.org.uk/* and http://www.blocked.org.uk/* are now 301 redirected to https://www.blocked.org.uk
- HSTS header is in place
- Cookie is modified to include "Secure" - i.e. the cookie will only be submitted over https to *.blocked.org.uk domains

**Comment by graphiclunarkid** [comment]
Good point about patching ModX, @gwire - undesirable!

Given that the Varnish work-around is working, and you've implemented the other changes on your list, I think we can close this now.
