### ISSUE TITLE
Update social media icons under "Spread the word"

### ISSUE THREAD

**Issue by Flatlyn** [openrightsgroup/cmp-issues#165]
Consider switching the icons to versions that fit better into the overall clean design feel of the site. 

Additionally change the Twitter icon to be the twitter bird rather than the "t" it is just now. The "t" is non-standard for a twitter link, with the majority of services using the bird, can be confused with Tumblr, and is not in fitting with Twitters brand guidelines.

**Comment by dantheta** [comment]
Thanks for the feedback.  I've changed the social icons to use the same vector set that is in use on the main openrightsgroup site.  This set uses the proper bird logo for twitter.

Thanks again,

Daniel.
