### ISSUE TITLE
Method not allowed error on signup

### ISSUE THREAD

**Issue by owenblacker** [openrightsgroup/cmp-issues#166]
Filling in the "Stay informed" box at the bottom of https://stage.blocked.org.uk/thanks?u=1&v=1 after requesting an unblock took me to https://stage.blocked.org.uk/signup with an HTTP error message: Method Not Allowed. The method is not allowed for the requested URL

**Comment by dantheta** [comment]
This is sort-of fixed now.  The signup form has been changed to an action button linking to the action.openrights.org site.  Unfortunately the CSRF protection on that form prevents us posting to their directly.
