### ISSUE TITLE
Clearer status for unsent messages

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#174]
Where website unblock requests have been logged, but not sent:

(1) Users should get at a second and third request to confirm their email, after a day and a week;

(2) If the request is not completed within two weeks, it should be discarded. The user should be emailed to tell them it has been discarded.

The admin system should record the complaint as "Not completed" or "Discarded" as appropriate.

**Comment by dantheta** [comment]
User verification status is now visible in the admin pages.

**Comment by dantheta** [comment]
Verification reminders are being sent.
