### ISSUE TITLE
Data integrity for categorisation types

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#179]
The categorisation interface allows users to delete categories and apply new ones. This may lead front end users to believe that a "categorify" or "DMOZ" category is derived from external data where it is in fact applied by ourselves.

It also would make it impossible for us to raise complaints to Categorify where we believe they have made a categorisation error.

We should ensure that our internal classification data is kept separate from the derived data.

**Comment by edjw** [comment]
Dan said this previously when I asked about this

>The trash button marks a category association as "disabled", mainly so that the automatic category importer doesn't re-import the same category next time it runs.  We can query for categories which have been disabled.  The category is currently still shown in the frontend, as it doesn't know about the enabled field yet.  That will change with the next API update.

>The backend knows which ones [categories] have been added by hand - I can add a marker to the UI to represent this.

**Comment by dantheta** [comment]
I was wondering about this yesterday.  I think we've got a site category 
list from the previous frontend which we can refresh and use here.

The administrator would only be able to add categories from this list, 
but could override/remove categories that had come from an external 
source.

With a small amount of effort, the category list could be maintainable 
from the control panel too.

Does that sound OK?

**Comment by JimKillock** [comment]
That sounds great. I think the user interface (front and back end) should be really clear about whose categorisation values are applied - ours, Categorifies, DMOZ or the ISPs.

**Comment by dantheta** [comment]
The category review screen can now only add values from the ORG category list.  It is possible to add values to this taxonomy on the fly (albeit only one at a time).  Should be OK for now though. 

The admin screen can still be used to suppress category mappings from the external sources.

I'll add another ticket for the frontend update - that's not too big a change.
