### ISSUE TITLE
Verify email addresses

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#18]
I think we need a generic system for verifying email addresses. We are already planning a couple of features that could make use of one:
- [Registering a probe user](https://wiki.openrightsgroup.org/wiki/Censorship_Monitoring_Project_API#POST_.2Fregister.2Fuser)
- Signing up for email reports ( #6 )

If we want to allow probe users to be anonymous we should build this feature explicitly rather than allowing them to register with non-existent email addresses.

Verifying email addresses could affect #9.

**Comment by graphiclunarkid** [comment]
Possibly of some use for this: http://stackoverflow.com/questions/7703200/how-to-write-a-php-double-opt-in-subscription-form

**Comment by graphiclunarkid** [comment]
After some thought I've realised we need to verify email addresses _together with action requests_.

Verifying that an email address is valid is necessary but not sufficient. We must also make sure the owner of that address actually wants to receive the emails to which it is being subscribed. Otherwise bad actors could (for example) request reports for a spam URL to be sent to verified addresses without further confirmation.

Proposed mechanism:
1. User requests a URL be checked, submits their email address, and asks for regular reports.
2. System concatenates the email address with a unique salt; hashes this string; and stores both the resulting token and the salt in a database table (see my comment on #6 for a suggested table structure)
3. System emails a URL of the form https://blocked.org.uk/verify.php?email=ADDRESS&token=TOKEN to the email address given by the user.
4. User clicks on the link, or otherwise requests the URL.
5. System looks up the salt for the token; hashes the email address with the salt; compares the result with the token; and sets the "verified" flag against both the request and the email address if they match.
6. System displays confirmation to the user that they have subscribed to regular reports for the URL in question. (It would be nice to include an "undo" button on this page).

**Comment by dantheta** [comment]
I've updated the wiki API docs with the proposed API endpoint for verifying an email token.

https://wiki.openrightsgroup.org/wiki/Censorship_Monitoring_Project_API#POST_.2Fverify.2Femail_.28proposed.29

I'll be reviewing the token verification branch tomorrow and possibly merging it then.

**Comment by dantheta** [comment]
I've got a new version of the branch for the email verification, so it might be best to hold off on reviewing the current one.

**Comment by dantheta** [comment]
The branch has been tested and merged - we're storing URL subscriptions in a slightly different way, but we're ready to be able to verify email addresses.  I'll open a new issue for creating the website page that users click through to from their email message.
