### ISSUE TITLE
Unspecified error page

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#183]
Please see: https://www.blocked.org.uk/control/ispreports/Vodafone/http://www.workersplaytime.net

Or, the following page (and select email number 2 to trigger the error): https://www.blocked.org.uk/control/ispreports/EE/http://www.filmhub.com

**Comment by alexhaydock** [comment]
NB: Please note that the error page does not always trigger for the same URL. For instance on the first URL it appears to only trigger for Vodafone. Other ISP pages for the same URL are unaffected: https://www.blocked.org.uk/control/ispreports/EE/http://www.workersplaytime.net

**Comment by alexhaydock** [comment]
Further note: It looks like this error appears for every Vodafone ISP report.

**Comment by dantheta** [comment]
Yep, this is because of the quoted printable fix.  Vodafone replies use windows-1252, not utf8.  I've added a quick fix for it (the infamous black diamond), and will add better charset handling when I'm fully back.

**Comment by dantheta** [comment]
Vodafone reports are readable in basic form.  I've spun off another ticket for handling charset more gracefully.
