### ISSUE TITLE
UX: Place "Review Block" tick in column on main ISP reports page also

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#187]
For my purposes it would be very useful if the tick which is displayed on the page for a block which has been reviewed (displayed next to the "Review Block" tab text) was also displayed in a column on the main "ISP Reports" page.

This would make it very easy to see at a glance which reports have and have not been reviewed.

**Comment by edjw** [comment]
@dantheta I think this is quite important for the efficiency of Alex's workflow. He needs to be able to tell quickly which reports have and haven't been reviewed. Can you take a look at this when you get the chance?

**Comment by ei8fdb** [comment]
Hi!

I've been <lurking> and following these issues for a few days. ;) If you'd like some UX input I'd be happy to help.

**Comment by dantheta** [comment]
The column has been added.
