### ISSUE TITLE
Allow filtering of reports to ISPs

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/cmp-issues#190]
Can we add the ability to filter reports to ISPs and the attributes we've added to them? This should be in the interface being used by Alex at the moment.

Priorities would be to be able to filter by **Category** and whether it had been tagged as **Add to Frontend**. It would also be good to be able to filter by whether it had been tagged as an egregious block and by ISP

We'd like to be able to quickly see all sites that have been reported and are in the category of charity for example.

Ideally, it would display the number of results returned when the filter is applied as well

**Comment by dantheta** [comment]
I've added state filter tabs for reviewed and featured, and dropdowns for category and ISP.

Adding totals to the categories is currently a bit too computationally expensive, but may be possible in the future.

The paging list at the bottom was a bit messed up during development, but should be fine now.  Let me know if there are any problems.

**Comment by edjw** [comment]
Thanks for the changes Dan. All good. 

It'd be useful if we could filter by either Reviewed or Not Reviewed. Can we add that? At the moment we can filter down to what we've done but not down to what we've not done. Maybe it could be a dropdown menu?
