### ISSUE TITLE
Add clarification on what the Flag button does

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/cmp-issues#193]
It's not clear what happens when you click the Flag button on the ISP reports page. Similarly to [the issue described here](https://github.com/openrightsgroup/cmp-issues/issues/184#issuecomment-464098949), can we add a tooltip or some copy to make it clear to a researcher using the admin area what will happen if they click the Flag button?

**Comment by ei8fdb** [comment]
@edjw could you give a screen shot of that page?

What (in long hand format...) will hapepen when a researcher clicks the flag button? 

Do they (the researcher) need a way to undo the act of flagging?

**Comment by edjw** [comment]
Thanks for this Bernard :-)

>What (in long hand format...) will hapepen when a researcher clicks the flag button?

When the researcher clicks the flag button, the ISP report is abandoned and no longer progresses through the unblock process. The final state of the report is marked as "abuse" to differentiate it from cancellation. We also use it when we see attempts to unblock obvious actual pornography sites and scams. Users can be scored negatively on the number of abuse reports they've submitted and possibly even get themselves blacklisted. The flag report feature also prevents the user's comment for the ISP report from showing on the front-end.

>Do they (the researcher) need a way to undo the act of flagging?
When the Flag button is clicked, it turns into an Unflag button.

Here's the screenshots of that page

_With nothing flagged_
<img width="1227" alt="nothing_flagged" src="https://user-images.githubusercontent.com/6547979/52960128-fd07d680-338f-11e9-93ed-2f2c4eaf7c75.png">

_With one report flagged_
<img width="1227" alt="flagged" src="https://user-images.githubusercontent.com/6547979/52960126-fc6f4000-338f-11e9-9fd7-5a81e5cf2bfa.png">

**Comment by dantheta** [comment]
I've added an ISP report state diagram here:

https://github.com/openrightsgroup/Blocking-Middleware/wiki/ISP-Report-submission-process

The flag button marks the ISP report with the status "Abuse".  It's intended to immediately halt processing of the ISP report (closing it), and to ensure that it can't count towards the unblocked or rejected statistics.  The URL would not be reportable against that network again.

The flag is intended to halt the processing of reports which are not suitable for unblocking, such as obvious known adult sites, or where the reporter is trying to link-farm or anything like that.  The comments attached to reports which have the **abuse** status are not published on the site.

In case of administrator error, the abuse flag can be reset, which returns the report to the **pending** or **sent** state.

This is probably a bit too much detail to include in a tooltip or info panel in the control panel UI, but might be suitable as a wiki or manual page.  Suggestions welcome!
