### ISSUE TITLE
Add categories for "Who?" and "Damage" to classify user reports

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#197]
After discussion with @jimkillock, it has been identified that it would be useful to be able to classify reports in the same way that URLs are currently classified using the categories feature on the "Review Categories" tab.

To classify reports, it would be useful to have two open-ended category labels that could be attached: "Who?", and "Damage".

"Who?" would be useful to classify reports based on whether they come from a site/business owner or a site user etc., and "Damage" would be useful to classify whether the report has cited any damage caused by the block (lost sales, customers complaining etc.)

Ideally, these tags would work the same way as the categories in the "Review Categories" section - in that they can be arbitrarily added by admins when required, or selected from a list for categories that already exist.

Thanks

**Comment by edjw** [comment]
What would be the possible choices to the questions of "Who made the report?" and "What, if any, damage was reported?"

**Comment by alexhaydock** [comment]
Likely:

#### "Who made the report?"
- Site/business owner
- Site/business user
- Webmaster / web developer
- Other / unknown

#### "What, if any, damage was reported?"
- Lost sales or suspected lost sales
- Users complaining about blocks
- Broken site content (in the case of a CDN/imagehost being blocked)
- Paid services inaccessible

But the idea of having an open-ended category like the "review category" currently functions is that admins could add these labels as they are required, even though I expect the list to stay fairly small.

**Comment by JimKillock** [comment]
The ‘damage reported’ probably needs to allow multiple options to be checked, as several may be cited

**Comment by alexhaydock** [comment]
For the purposes of the research this ticket will help with, #198 is also particularly important and (hopefully) is an easy addition.

**Comment by edjw** [comment]
Can we also expose the data from the report stage where the reporter clicks a checkbox saying one of: I am a user/I am the owner/ someone who cares about censorship? This would be useful information for Alex while he's doing this research

**Comment by dantheta** [comment]
I've deployed a first pass at this - there may be some rough edges or bugs but they should be fairly easy to take care of tomorrow.

I can't find the site owner/user datain the system at the moment - I'll keep looking.

**Comment by alexhaydock** [comment]
This is working well seemingly, thanks Dan.

The only issue I'm running into is the fact that it stores the data per-report rather than per-URL. As the actual report text and content is the same across all of the ISPs that a single URL is reported to then it makes more sense to me to store this data just once for each URL.

**Edit:** For now I am categorising the user-submitted text for the URLs in the database with this new tool, but I am ensuring that I do that categorisation process on only one ISP report entry per URL, no matter how many ISP reports belong to each URL.

Hopefully this means it wouldn't be too difficult for you to take the data I've entered and move it to apply it to the URLs rather than just the individual reports? That's my hope anyway.

**Comment by dantheta** [comment]
On 2019-02-21 10:54, Alex Haydock wrote:
> This is working well seemingly, thanks Dan.
> 
> The only issue I'm running into is the fact that it stores the data
> per-report rather than per-URL. As the actual report text and content
> is the same across all of the ISPs that a single URL is reported to
> then it makes more sense to me to store this data just once for each
> URL.

Yep, that makes sense.  I can change that and move the data that's been 
added so far.  If you want to just only use these fields for one report 
of a given URL, that would be fine for now, and the shared view should 
be available tomorrow.  I should also have time to tidy up the UI a  
tiny bit.

When we start allowing reports to be cancelled and re-filed by a 
different user, we may find that an assigned reporter category is out of 
date.  The comments log should serve as a historical explanation for 
those changes though.

**Comment by alexhaydock** [comment]
I love the _"User domain matches target domain"_ feature! Very useful time saver.

Are you able to tweak it with some kind of wildcard that ignores a leading `www.` in the domain?

**Edit:** Maybe I mistook this as an automated feature where in fact it's entries you've added manually for testing.

**Comment by alexhaydock** [comment]
> On 2019-02-21 10:54, Alex Haydock wrote: This is working well seemingly, thanks Dan. The only issue I'm running into is the fact that it stores the data per-report rather than per-URL. As the actual report text and content is the same across all of the ISPs that a single URL is reported to then it makes more sense to me to store this data just once for each URL.
> Yep, that makes sense. I can change that and move the data that's been added so far. If you want to just only use these fields for one report of a given URL, that would be fine for now, and the shared view should be available tomorrow. I should also have time to tidy up the UI a tiny bit. When we start allowing reports to be cancelled and re-filed by a different user, we may find that an assigned reporter category is out of date. The comments log should serve as a historical explanation for those changes though.

Ah yes thanks :) I edited my reply above after sending but notice you're on email rather than GitHub so probably didn't see it. I added:

**Edit:** For now I am categorising the user-submitted text for the URLs in the database with this new tool, but I am ensuring that I do that categorisation process on only one ISP report entry per URL, no matter how many ISP reports belong to each URL.

Hopefully this means it wouldn't be too difficult for you to take the data I've entered and move it to apply it to the URLs rather than just the individual reports? That's my hope anyway.

**Comment by dantheta** [comment]
I wish the system could claim credit for that one - that was actually me 
testing the record addition by hand :(

It's a good feature idea though.  I should be able to update those 
programmatically.

**Comment by alexhaydock** [comment]
> I wish the system could claim credit for that one - that was actually me testing the record addition by hand :( It's a good feature idea though. I should be able to update those programmatically.

Yeah, I started to figure it might be after I poked through a few more with email domains that matched their URLs and saw it didn't appear on them. Oh well, maybe a useful feature for the future if it's easy enough to add. :)

**Comment by alexhaydock** [comment]
Hi @dantheta 

Just in case you're planning on working on this tonight - are you able to add some form of function allowing me to sort by the "damage" and "reporter" categories?

It doesn't really have to be anything that integrates nicely into the UI yet and could just be on a seperate page somewhere for now if it doesn't make sense anywhere else. But just some function allowing me to see all of the entries which have been placed into each category would be super useful for me to keep working on this research tomorrow.

Thanks :)

**Comment by dantheta** [comment]
The URL reporter category records have been moved across to url-level, and should be shared between reports for the same URL.  I haven't been able to do the listing page tonight, but I might have time tomorrow morning.

**Comment by alexhaydock** [comment]
Seems to be working well. Thanks. :+1: 

A listing page would be useful if you do get the chance but there are other things I can work on for the time being so no major rush.

**Comment by alexhaydock** [comment]
Everything in this ticket has been resolved as far as I can see. Closing.
