### ISSUE TITLE
Add "Next URL" button to ISP Report page

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#198]
For the purposes of classifying the content of reports rapidly as discussed in #197, it would be very useful if there was a button on the ISP report page that advanced to the report page for the next URL (most likely the next one reverse-chronologically).

This would save me from needing to maintain an open ISP Reports tab and keep opening new tabs while classifying reports.

**Comment by dantheta** [comment]
The next report button has been added.  It doesn't have access to the full state of the isp reports listing (filters etc).

**Comment by alexhaydock** [comment]
Hi, Dan. This is pretty much perfect. Thanks :+1: 

I'm not quite sure what you mean by it not having access to the "full state"? Seems to work just how I imagined.

**Comment by edjw** [comment]
Is there anything left with this ticket? Can it be closed!

**Comment by dantheta** [comment]
Nope, I don't think so.  I was wondering if the next isp button should pay attention to any filteres that were set on the listing page (which was what I meant by not having access to the full state of the listing page), but it sounds like that isn't required at this point (and it would be quite complicated to do).
