### ISSUE TITLE
Copy for results email

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#2]
When a user submits a URL for checking they can opt to provide an email address to which results will be returned. We need a template for this email.

**Comment by RuthC** [comment]
If this isn't where ideas go for this, please can someone reply & let me know!
I've written a basic idea of what kind of content I think should go in such an email. 

Question: Who should this email come from? 
Best practice for ORG is always to name a person an email is from. They get better open rates and feel more 'real' that way. 

Dear X

Thank you for using the blocked.org.uk Censorship Monitoring Tool. 

Our tool searches the six main ISPs for blocked websites under the current system of Internet filtering.

Your results for XXXX website have been returned below. 
REPORT

Would you like to tell us more about these results? The Censorship Monitoring Project exists to document UK censorship. If you'd like to share your story about how filtering has effected you or your business, please email XXX

This tool is only available thanks to volunteer efforts. If you can give a tip, please donate a little to help keep this project going. DONATE LINK 

If you'd like to report another website block, or check another site please submit again. 

Kind regards,
The Blocked.org Team

**Comment by graphiclunarkid** [comment]
This is a great place to discuss ideas for this - thanks!

I really like the template you've provided. It takes the opportunity to explain what the site does (and therefore what the results do and don't mean). It also doesn't miss the opportunity to ask for donations :-)

Excellent point about the person from whom the email should appear to come. I don't have an answer but I can start a discussion with some options off the top of my head:
- "The blocked.org.uk team" (represents the community that did the work, but is abstract - not good practice as per the question).
- A blocked.org.uk contributor chosen randomly from a list (Only include contributors who want to be included! Gives credit where it's due. Not good if we want to handle replies).
- ORG's supporters officer (many other ORG communications to supporters come from this role - though not all visitors to blocked.org.uk will be supporters)
- ORG's executive director (the most public-facing ORG figure, gives authority to the communication, but a bit disassociated from the project?)

Thoughts?

**Comment by RuthC** [comment]
The other person you missed off that list is of course yourself. :)
Richard King, Project Co-ordinator (?)

I guess we also want to think about who is going to manage the blog and the reports. 
That may well be Pam or Javier? 

Personally, I don't think the ED is the right person for the email to be from. It's unlikely to be in his tone and I feel should come from someone who would be responsible for dealing with the replies as well.

**Comment by graphiclunarkid** [comment]
I'm happy to be the person by whom the messages are signed. Perhaps it can be "on behalf of the @openrightsgroup/cmp team" though? I'm fine with taking responsibility for the project as long as I don't appear to be taking all the credit!

It might be useful to use a separate inbox (e.g. blocked at org dot org) rather than my own account. Then if there are many messages others can help out with the responses.

A generic (blocked at org dot org) address might also be useful for features such as #6 that use email as their mechanism.

**Comment by RuthC** [comment]
I agree with all of that. I like the team sign off.

**Comment by graphiclunarkid** [comment]
I have asked Lee to set up blocked at org dot org as an account on ORG's mailserver.

**Comment by JimKillock** [comment]
I'm just reviewing this, and I'll ask Pam what she thinks but I'd say that it's a huge opportunity to promote ORG in whatever way we can with these emails. There's an argument that an email from ORG might confuse the recipient but it seems a shame to diminish ORG's involvement by missing the opportunity to show we are responsible for the project. The copy too, while very readable doesn't really say much about ORG or why you should donate to us.

**Comment by pamcowburn** [comment]
Lee has set up blocked@org.uk - it will come to me, Jim and richard.
I think the email should come from an individual. Prob makes sense if it's Richard but needs to be ORG - branded. 

One branding question - to fit with logo think we should refer to blocked as Blocked! when writing it in text or refer to it as blocked.org.uk - any preferences?

Here is content for the email:

Subject: Blocking results for [url] from Open Rights Group

You asked Open Rights Group to send you updates about whether [insert
URL] is blocked by filters.

Here are your updated results:

What you can do now:

If you'd like to share your story about how filtering has affected you
or your business, please email blocked@openrightsgroup.org
mailto:blocked@openrightsgroup.org

If your site has been blocked, visit blocked.org.uk/unblock for information about how
to contact broadband and mobile providers.

If you would like to join the ORG's mailing list, please subscribe here. [CAN WE LINK TO THIS?]

You can share your results on Twitter, Facebook or GooglePlus.

Open Rights Group campaigns for your digital rights. We are able to provide tools such as blocked.org.uk
for free, thanks to our amazing supporters, sponsors and volunteers. You can support this project by making a donation, joining Open Rights Group or getting involved as a technical
volunteer.

DONATE BUTTON [link to new join/donate page]
Thanks for using Blocked.

Best wishes

Richard King

Project Manager
Open Rights Group

**Comment by dantheta** [comment]
This has now been loaded in.  I've made some slight modifications as the email report is currently formatted as a daily summary of activity on all URLs that an individual has subscribed to.
