### ISSUE TITLE
Direct navigation to thankyou.html displays content-less results page

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#20]
Reproduction steps:
1. Type "http://stage.blocked.org.uk/thankyou.html" directly into the address bar and hit <enter>

Expected: Site redirects to http://stage.blocked.org.uk/

Actual: Site displays the thankyou page for the URL "http://"

**Comment by mkillock** [comment]
Fixed - now redirects to MODx site_url setting - currently stage.blocked.org.uk

**Comment by mkillock** [comment]
The SubmitUrl snippet does the redirection

**Comment by graphiclunarkid** [comment]
:grinning:
