### ISSUE TITLE
Expose statistics for report categories

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#200]
Hi @dantheta. Thanks for adding the report category labels. I have finished categorising them now and this data will be very helpful for our report.

Further to what I mentioned in #197, it would be very useful if the interface could expose some statistics about the categorisation of reports.

It would still be useful to have the option to filter allowing me to see all the entries which are members of each category, but exposing some statistics would probably be helpful.

For example:

* Number of reports in each category
* Number of reports in each category over time (Last 7 days, Last 1 month, Last 3 months, Last 6 months, Last year)

@jimkillock if you are able to add any further suggestions for statistics which would be useful that would be ideal. Thanks.

**Comment by JimKillock** [comment]
I think a provider by time breakdown would be helpful also. An annual stat would be fine.

eg: BT, by complainant and by damage category for 2017, 2018 and 2019.

An aggregate figure for mobile and fixed (at default setting, ignoring BT Strict) also by year would also be elucidating.

Personally I think we should default to annual stats rather than smaller periods for all the figures, as this will make for easier comparison, and the numbers could be rather low in many reports otherwise.

These stats, as for the other statistics ticket, will ultimately be bound for the public site, whether as raw numbers or pie charts, graphs, etc.

**Comment by JimKillock** [comment]
Note to flag that this ticket and https://github.com/openrightsgroup/blocked-org-uk/issues/372 are in my view next up as we will need the information early next week to do the write up.

**Comment by dantheta** [comment]
Added a report stats page (linked from the admin panel top-level NAV for the moment).

There are two summary tables, and the full detail table.  Export to CSV is also provided for the full detail table.

**Comment by JimKillock** [comment]
Thanks very much Dan, that looks great. 

I think my ticket must have been unclear tho in one aspect. I meant to have the reporter type by network per year *and separately* a breakdown of damage type per network per year.

Doing both at once presents a bit too much information which isn't easy to draw conclusions from.

**Comment by dantheta** [comment]
No problem, that's updated.

**Comment by JimKillock** [comment]
Thanks Dan. Can we 

[] 1 group the stats (default sort) by ISP (so we can look at the results for each ISP all at once). 

[] 2 Add a table for  "total reports per year by ISP". Have a subtotal for mobile and fixed networks

[] 3 Add a total row for table 1 "Reporter Summary", showing "total reports per year / all time"

**Comment by dantheta** [comment]
Those updates are done.

**Comment by alexhaydock** [comment]
I'm just looking at this trying to work out how best to present this data in graphical form and I'm wondering whether the "Damage Summary" output is counting +1 for every report of a URL per-ISP rather than per-URL.

I ask only because I was reasonably certain that I only applied the "Block has directly influenced business decisions" to one or two sites and yet it appears to be counting "7" in the Total column for that one.

**Comment by alexhaydock** [comment]
@JimKillock 
> 
> Personally I think we should default to annual stats rather than smaller periods for all the figures, as this will make for easier comparison, and the numbers could be rather low in many reports otherwise.
> 

I generally agree when it comes to presenting raw figures in reports or to end users, though I'm finding that it’s difficult to present per-year graphs that display meaningful trends without either month-by-month granularity or without excluding 2019, as we’ve only had 2 months worth of 2019.

But a lot of our data is centred around 2018 and none extends back to before 2017 so we can’t really do a year-on-year growth/decline line or bar chart as we’re limited to only two bars or points to extrapolate from.

Realistically speaking if we're plotting by entire-year we don't even have a complete dataset for 2017 so we'd end up with a single bar on the graph, so I'm thinking maybe we need to expose more of the data on the _ISP Report Stats_ page, even if it's just in the CSV download. Then I can start using that to draw some trends.

**Comment by JimKillock** [comment]
I think this is simply a fact: we don’t have enough data to see trends yet. We shouldn’t therefore talk about trends yet, but instead concentrate on the 2018 data to show what we know about what took place that year.

The coding though should reflect our needs in the medium term.

**Comment by alexhaydock** [comment]
Okay, I will focus the graphs onto breaking down what we saw in 2018.

**Comment by edjw** [comment]
Is there anything left to be done on this ticket?

**Comment by edjw** [comment]
@dantheta Can you clear this question up? https://github.com/openrightsgroup/cmp-issues/issues/200#issuecomment-466969571

**Comment by dantheta** [comment]
> I'm just looking at this trying to work out how best to present this data in graphical form and I'm wondering whether the "Damage Summary" output is counting +1 for every report of a URL per-ISP rather than per-URL.
> 
> I ask only because I was reasonably certain that I only applied the "Block has directly influenced business decisions" to one or two sites and yet it appears to be counting "7" in the Total column for that one.

Yes, that's right.  The summary is multiplying flagged URLs by the number if reports logged against it.  This probably isn't what you're looking for on the summary lists.  I'll get that changed now.

**Comment by dantheta** [comment]
That's updated now.

**Comment by alexhaydock** [comment]
Great, thanks. :+1:  I think this one can be closed now if that's okay with you @edjw / @dantheta
