### ISSUE TITLE
Add all MHRA-registered sites to test list

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#202]
We've seen queries released to pharmaceutical companies being categorised as "Drugs" and then being blocked on the assumption that they are promoting illegal drug use.

Can we pull a list of all MHRA registered websites and test them.

MHRA has a registry, I can't find an API, but there's a website with 830 entries
https://medicine-seller-register.mhra.gov.uk/search-registry/?q=

Each entry will have zero, one, or more that one URLs - although the display is just the domain, the links are often full URLs. e.g. "www.ebay.com" is displayed with the link going back to a specific eBay seller.

**Comment by dantheta** [comment]
Lee has already loaded these.  Many thanks!
