### ISSUE TITLE
Virgin Media non-responsiveness

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#203]
Can I check what the email address we are using for Virgin is? 

I will follow up with them about their non-responsiveness.

**Comment by dantheta** [comment]
On 2019-02-25 13:14, JimKillock wrote:
> Can I check what the email address we are using for Virgin is?
> 
> I will follow up with them about their non-responsiveness.


Reports are being sent to: websafefeedback@virginmedia.co.uk
