### ISSUE TITLE
Expose more statistics

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#205]
Thanks for your work on #200, Dan.

I've identified some more statistics that would be useful for me to be able to pull out as this report continues being worked on.

* Number of reports with zero replies after (x) time period.
* Number of reports unblocked upon request (tagged in DB).
* Number of reports continuing to be blocked upon request (tagged in DB).
* Average time for ISP to reply. (though is this useful if most of the initial replies are automated?)
* Response rate of ISPs. (Again, how do we exclude automated replies?)
* See about getting the data from the radio buttons that users select when filing reports. 
    * This might help us further break down the reports in the “Not Stated” category as currently I’m just basing that data on whether the user stated who they were in the main text of the report.

**Comment by edjw** [comment]
@dantheta As I understand it, this is is addition to the [stats requested here](https://github.com/openrightsgroup/blocked-org-uk/issues/372).

Some of the requests may need some thought given the automated replies issues Alex mentions

**Comment by JimKillock** [comment]
Some of the above may be duplicated in https://github.com/openrightsgroup/blocked-org-uk/issues/372 - or at least that is the purpose of that ticket to my mind. 

For instance 372 tries to estimate the time taken for ISPs to respond, when responses have not been made at all, what the response rate is. I tried to indicate a methodology also: @alexhaydock could you read through that ticket and check whether it does what you want here?

**Comment by alexhaydock** [comment]
After looking at the new "ISP Reply Stats" page then yes I do think everything I wanted particularly for the graphs I intended to work on today has been added. Great :+1: will close this.
