### ISSUE TITLE
Allow filtering by categories assigned to reports

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#206]
The ability to filter URL reports into the category labels they have been assigned in the "Who?" and "Damage" would be very helpful.

I need this to be able to go back through the “Site Owner” tag and split it out into “Site Owner (Business)” and “Site Owner (Personal)” categories. This is useful to confirm a hypothesis that business owners are disproportionately reporting their sites as blocked whereas owners of personal sites aren’t doing it as often.

**Comment by edjw** [comment]
This is an important one for the report stats

**Comment by dantheta** [comment]
This has been added.  It was done in a little bit of a hurry, so combining it with other filters on the same control panel page may have slightly strange results at times.  If there are glaring bugs let me know.

**Comment by JimKillock** [comment]
Thanks, on a scan of the "Avg reply interval (WIP)" in my email, ignoring non-replies, most replies seem to take around 3-5 days. I think our methodology may be off therefore: are we including the time taken for non-responses for instance? I think we should only measure the response time where a response has been given.

It's clear that a bunch of email requests go missing and never get answered, but from a service perspective that is a different problem from taking a long time to reply.

**Comment by alexhaydock** [comment]
Thanks @dantheta - working nicely :+1: 

I don't really need to combine this one with other filters. It's mostly just for pulling out extra granular data and splitting some categories we already have down even further. I've not encountered any bugs yet so fingers crossed! :crossed_fingers:
