### ISSUE TITLE
Migrate version of form to version 1

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#21]
It would make sense for the current blocked.org.uk form to be replaced by the new version so that we de-spam the submissions, and enter the submissions directly into the database (while not displaying the results for now).

**Comment by mkillock** [comment]
The easiest way to do this for now would be to keep the current form layout and change the submission process - is that OK? Also note that this will change what is saved into FormSave, so is that going to be a problem? i.e. we'll have all these formats:
- the current blocked.org.uk formsave format
- the replacement blocked.org.uk formsave format (with 'name' field, hashes for url/email)
- the new.blocked.org.uk formsave format with different (with no 'name field', hashes for url/email)

**Comment by JimKillock** [comment]
Ok, I'm not sure what different with new. and stage. but for now I've put the new. form onto www.

TBH most of the form save stuff is not AIUI important, what's important is getting the data into the back end.

Where FormSave is helpful is with the user stories.
