### ISSUE TITLE
Remove user email address from blocked.org.uk body ext

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#210]
The email body text sent to ISPs contains the user email, eg "Website blocking enquiry from xxxx@gmail.com, regarding the website at
http://www.cfrsandiego.org."

Can we remove the email address, as some of the ISPs seem to be using this instead of the blocked.org.uk reply-to. This obviously may invalidate some of our conclusions about responsiveness. O2 in particular say they have been doing this.

**Comment by alexhaydock** [comment]
I will ensure we include this as a caveat in the body of the report and address it accordingly.
