### ISSUE TITLE
More ISP statistics

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#211]
For the purposes of this upcoming report, it would be very useful to have up-to-date statistics on the blocks by ISP.

This does not necessarily have to be exposed in the admin panel as a continually up-to-date page as it is just for the report at the moment (but if that would be easy enough to do then it might be useful).

For each ISP, I would like to know the:
* Number of sites tested by us
* Number of sites found to be blocked (currently)
* Number of blocks unique to that ISP (currently)

**Comment by alexhaydock** [comment]
Similarly, it would be useful to have the statistics for the number of sites which we have found are currently blocked by only one ISP, or only two ISPs (excluding BT-Strict).

**Comment by dantheta** [comment]
These are too slow to generate on-demand in the frontend or in the admin panel.

I've emailed a drive link containing the reports.

**Comment by edjw** [comment]
Can we close this now?

**Comment by alexhaydock** [comment]
Yes this can be closed.
