### ISSUE TITLE
Statistics for blocks which do/don't match ISP policy

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#212]
For the purposes of the upcoming report, it would be very useful to know what percentage of reports which we consider "unresolved" are also wrongful blocks (so that we eliminate reports for sites which we feel are within ISP policy to be blocking).

I'm open to suggestions on how to present this, but it seems to me that the easiest method for now would be if you would be able to add a column to the "Reply stats by network", @dantheta, which shows a figure for blocks which meet **both** of the following criteria:

* **is** considered "unresolved"
* **is** tagged with "Block does not match the ISP's policy"

It would also be quite useful to have this as a row in the "ISP Reply Stats" table at the top, which shows the total number of unresolved reports which do not match ISP policy.

**Comment by dantheta** [comment]
Non-policy blocks unresolved now added to both tables.

**Comment by edjw** [comment]
Can we close this now?

**Comment by alexhaydock** [comment]
Yes this ticket is done, thanks. Closed.
