### ISSUE TITLE
Mobile inconsistency complaints tool

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#214]
I think as part of this project we should do the following:

(1) Create an "inconsistency" list for any block on a mobile network where not every provider blocks the website

(2) Listings should be listed by numbers of blocks, low to high (one, two, three)

(3) Listings should be sortable by provider

(4) Link this to the public reporting tools

(5) Provide a statistical breakdown 

(a) Sites blocked by only one, two, three providers;

(b) numbers of inconsistent results per provider.

**Comment by JimKillock** [comment]
Further thought on this. We may find that some of the numerical inconsistencies are due to incomplete testing (this is a bit inevitable as the testing regime is prioritised for speed and throughput).

We might want to create some "test lists" which correspond to the inconsistencies within the mobile networks, eg "all sites with one mobile block", "all sites with two or three mobile blocks" for us to schedule some retesting.

**Comment by dantheta** [comment]
Creating a dynamic list against the full resultset was too slow for a live page.  I've added code that populates a set of saved lists, and linked them from an admin page.

There are also two stats graphs on the page.

**Comment by edjw** [comment]
Can this be closed now?

**Comment by dantheta** [comment]
Yep.  The data was generated as a one off, but I've got the scripts that can be used to re-run the lists should we want to revisit these (or run them as monthly reports or something)

**Comment by dantheta** [comment]
Reverted
