### ISSUE TITLE
Allow filtering ISP reports by damage category

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#216]
Much the same as #206, it would be useful if there was also a filter for the categories of damage that have been assigned to some ISP reports.

**Comment by JimKillock** [comment]
Quick note to say this would be very useful this eve ;)

**Comment by dantheta** [comment]
This has been added to the report category filter dropdown.  The reporter and damage categories are listed there under headings.  It should be OK until we've got lots and lots of categories.

**Comment by alexhaydock** [comment]
This has been working great, thanks. :+1: Closing.
