### ISSUE TITLE
Allow filtering by sites which do not have an ORG-assigned category

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#217]
I want to ensure that all domains have at least one category assigned by ORG.

So far I have left quite a number of these unedited where the category info pulled in from DMOZ or Categorify has been largely accurate.

But now it would be helpful if I could see a list of all of the domains for which we do not have an ORG-assigned category.

Additionally, it would be helpful if a page somewhere displayed all of the currently-assigned categories, and the count of the number of URLs in each category. (It's true that some URLs are in multiple categories and will therefore be counted more than once but in conversation with @JimKillock we've determined this won't pose too much of an issue).

**Comment by dantheta** [comment]
There's now an (unassigned) option in the site category filter dropdown.

**Comment by dantheta** [comment]
And a category usage report at: 

https://www.blocked.org.uk/control/ispreports/category-status
