### ISSUE TITLE
ISP category status report

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#219]
This is great:

https://www.blocked.org.uk/control/ispreports/category-status

Alex is aiming at adding information about the categories that user reports belong to. This presumably should include the 'categorify' information, or else we need to combine both sets of information into a report.

For now I'll just leave this ticket up, and Alex, if you can clarify if you have what you need, that would be very helpful.

**Comment by alexhaydock** [comment]
@JimKillock Well my intent as per #217 was to go through and ensure that all URLs had an ORG-assigned primary category, so I feel that if we are including Categorify data in the report then we need to work on somehow deduplicating the results. Simply listing out the Categorify categories on this page too will result in us counting URLs multiple times across the ORG-assigned and Categorify-assigned categories, surely?

Unless that is what you mean, in which case I don't think there's anything I immediately need for now, but will use this ticket if I uncover something.

**Comment by dantheta** [comment]
I'll close this one, if that's OK.  If more requirements for the category status report emerge, feel free to reopen/submit new.
