### ISSUE TITLE
Page to show the categories assigned to URLs within a particular reporter category

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#223]
The [ISP Report URL Category stats](https://www.blocked.org.uk/control/ispreports/category-status) is very helpful.

It would be helpful if we had a feature on this page that allowed a filter to be added which showed the totals for all of the ORG-assigned categories - as the page currently does - but limited the displayed totals only to URLs tagged with a user-selectable "Reporter Category".

If this is too much work, then the shortcut that just exposes the particular data I need for the report right now would be to create a page that's just like the above one but only shows the totals for URLs which have been tagged with "Site Owner (Business)". I need this data to graph exactly what kind of business owners we're getting reports from.

Thanks :+1:

**Comment by alexhaydock** [comment]
Nobody is around to bump this ticket or assign it into the right category but @dantheta, if you see this, I'd consider this one a fairly high priority.

**Comment by dantheta** [comment]
On it :)

**Comment by edjw** [comment]
This is done and can be closed right?
