### ISSUE TITLE
Rename "Advertising, Branding, and Graphic Design"

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/cmp-issues#224]
Hi Dan,

I made a mistake and created two categories which I've been putting Graphic Design sites into:

* Advertising, Branding, and Graphic Design; and
* Photography, Graphic Design, and Filmmaking

Are you able to rename the "Advertising, Branding, and Graphic Design" category to just "Advertising and Branding" please? Thanks.

**Comment by dantheta** [comment]
That's done!

**Comment by alexhaydock** [comment]
That was quick - thanks :)
