### ISSUE TITLE
Add "OrG Category" to ISP Report Admin

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#226]
On the list view, add a column stating the ORG Category/ies assigned:

https://www.blocked.org.uk/control/ispreports

This will help us check we have completed the categorisation process and data.

**Comment by edjw** [comment]
Would this filter help with checking how complete the categorisation process is? It shows all reported sites without an ORG category
https://www.blocked.org.uk/control/ispreports?category=_unassigned_&state=

**Comment by JimKillock** [comment]
Yes I think that's good enough, thank you.
