### ISSUE TITLE
ISP Report Admin: remove abuse, unsent, ORG

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#229]
On the ISP Report Admin, could we (have an option to) exclude reports that are either:

(1) Flagged as abuse

(2) Not sent as unverified etc

(3) Listed as "ORG" (I'm not sure what that means)

This would speed up going through the reports

**Comment by dantheta** [comment]
The "Open" filter button on the ISP reports list is pretty close to this (apart from the "ORG" entries).

The Site feedback (broken/parked/etc) works by filing an ISP report to ORG as a pseudo-ISP.

**Comment by JimKillock** [comment]
Thanks, that helps for the most part. 

If there was a way to get the next / previous report button on the site report view (Report details) to follow the choices I've made that would make my life easier too.
