### ISSUE TITLE
Ensure stats exclude various categories

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#230]
Particularly:

* "ORG ISP"
* Reports that were not sent to the ISP as the user was not verified ("Awaiting user verification")
* Reports not sent because they stayed in the queue ('Pending")
* Reports that were cancelled
* Reports marked as abuse

Reports with these statuses should be ignored when calculating ISP performance, category totals, kinds of reporters, etc.

**Comment by JimKillock** [comment]
We should exclude BT Strict from the totals of sites affected, or present those separately. It can stay for performance stats.

**Comment by dantheta** [comment]
I've updated the stats pages to disregard new, pending, abuse, cancelled ISP reports (leaving only sent, unblocked and rejected).  The BT-Strict ISP is still present on reports that list per-ISP totals.  

* BT-Strict and ORG are not counted in the rolled-up (not per-ISP) totals tables.
* ORG  pseudo-ISP is excluded from per-ISP tables.

**Comment by dantheta** [comment]
Is this working OK?

**Comment by JimKillock** [comment]
We think so!
