### ISSUE TITLE
Renaming or merging categories

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#231]
In the categories, there are a few spelling errors, and some categories are slightly mis-named, eg 'arts' should be 'arts and crafts'.

Some categories should be merged.

What is the best way to do this @dantheta?

**Comment by dantheta** [comment]
I've added a set of category management screens (under the URLs menu) to allow editing, deleting and merging URL categories.  Data from dmoz and categorify can't be edited from here, only ORG-assigned categories.

**Comment by JimKillock** [comment]
Excellent, I am hitting a bug just now on saving a change ("Bad Request
The browser (or proxy) sent a request that this server could not understand.")

**Comment by dantheta** [comment]
That's fixed now.
