### ISSUE TITLE
Remove "Recently reported sites" block

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#235]
This will be superceded shortly, but is misleading currently so we should remove it meantime.

https://www.blocked.org.uk/reported-sites

**Comment by edjw** [comment]
Do you mean we should take the page down @JimKillock ?

**Comment by JimKillock** [comment]
No, just the "Recently reported sites" block on that page. The figures are misleading and will be superceded in the report, however the list of reports is fine.

**Comment by edjw** [comment]
Ok, so the headline and table at the top of that page.

How about we use the word 'section' rather than 'block' when we're talking about part of a webpage on this project!? 😄

**Comment by JimKillock** [comment]
I'll try to remember that!

**Comment by dantheta** [comment]
The stats section was removed in one of the other tickets, I think.  The page just contains the reported sites list.
