### ISSUE TITLE
Admin user random names

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#237]
Virgin seem incapable of sending single replies for unblock requests. To combat this, it would be helpful if a logged in admin user sent out emails with random names to them so they cannot be matched / assumed to belong to one person.

**Comment by JimKillock** [comment]
Flagging this problem to you folks. We could as an interim measure, strip the user name for Virgin emails, and replace it with "Blocked user <string>".

and also add "Please reply directly to the user at this email address to ensure that they receive your response. Do not combine responses as they will be sent to the wrong person."

**Comment by edjw** [comment]
We should at least test that approach in the second comment to see what happens.

**Comment by dantheta** [comment]
I just wanted to clarify this part of the issue text:

> logged in admin user

On first reading, I'd thought this meant it should be part of the 
planned feature to allow an admin to force through an ISP report (even 
if the original reporter was unverified, etc).

Should it mean:

1) Admins using the backend system to force through a report to 
VirginMedia
2) Admins using the frontend system to submit a new ISP report to 
VirginMedia
3) Everyone using the frontend system to submit a new ISP report to 
VirginMedia

?

**Comment by JimKillock** [comment]
I think (3) is best. On a second, third, etc report in a 4 week period, all the subsequent emails to Virgin should be anonymised. They can be called "Blocked User 1234" for now.

**Comment by JimKillock** [comment]
Flagging that this would ideally be done soon, in case we get a flurry of complaints

**Comment by dantheta** [comment]
I've added the "please do not aggregate replies" message for VM, and there is now a checkbox on the unblock form to allow admins to opt for a random name, so that we can trial it before wider use.

At the moment, the random name is selected each time a report is submitted, and is used in all of the ISP emails for that site.  It isn't currently restricted to just VM.

There are about 200 random names in the system, and it's easy to add more.

**Comment by JimKillock** [comment]
This seems to be working well for admins. I wonder though how it would seem to front end users. It would need explanation. Maybe if Virgin's behaviour improves we can keep the feature just for admins (it's useful to appear like Joe Random in any case).

**Comment by dantheta** [comment]
I've been thinking about the public user case a bit.  There have been some entries where the user has included their real name in the comment section.  Having an email name that conflicts with that would look very weird.  In cases where the site owner is raising a complaint (and includes their name & relationship-to-site in the comment field), we would lose a lot of the impact if we were to mask the regular user.

I think we can switch it to default-on for admins though.  We'll have to monitor VM and see how useful it is there.

**Comment by JimKillock** [comment]
Perhaps for end users we could simply remove the name for Virgin Media and "Blocked User No 1234"?

That would not require explanation, etc. Occasionally it would lose impact for Virgin. However as they are slowest, this does not matter much.

This would depend on treating the email 'from' line slightly differently per ISP.

**Comment by dantheta** [comment]
Looking at the most recent Virgin Media responses, I think they've understood that each email/report/url is a separate case.  There are still a lot of reports that they haven't responded to at all, but they haven't combined responses since June 2018.  Using the intermediate reply-*@blocked.org.uk seems to have fixed things there.

**Comment by JimKillock** [comment]
They did merge a bunch of requests I had made in January. They saw my real email from a different source, and then merged the reply. So for me it's a bit of an open question!

On another note, the random name feature could be useful for other bulk filing reports, for instance relating to VPNs or CBD sites for review, should we wish to do that.
