### ISSUE TITLE
Lists: add ISP filter

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#241]
Can we add a filter for the lists creation, that allows us to create a list of blocks relating to:

(1) Any mobile operator; or

(2) Any non-mobile operator; or

(3) Any specific network

This will help us build lists of errors that are relevant to specific ISP / mobile policies.

**Comment by JimKillock** [comment]
Add: can we also add a filter for .uk results only.

**Comment by dantheta** [comment]
Currently rebuilding the search index to include TLD and blocking network fields.  This will allow the search engine to filter on these during list build and regular keyword querying.

**Comment by JimKillock** [comment]
Thanks Dan. 

Could we also apply these criteria to an existing list - for instance by applying the search to a particular already existing list?

**Comment by dantheta** [comment]
Yep, that's planned.  Filtering search and filtering existing lists use two separate facilities in the code, but they're both in progress.

**Comment by dantheta** [comment]
Search results can now be filtered by individual network.  The network selection is carried through to saved list creation too.

The mobile and fixed line options don't work yet.

This may require a bit of testing!

**Comment by dantheta** [comment]
Filtering saved lists by ISP is now live.

all-mobile and all-fixed options to follow.

**Comment by dantheta** [comment]
> Add: can we also add a filter for .uk results only.

This one's a bit trickier.  I'd suggest splitting that off to a separate issue.

**Comment by dantheta** [comment]
fixed and mobile options are working.  BT-Strict is inflating the fixed counts quite a bit.

**Comment by JimKillock** [comment]
Hi Dan, reviewing this ticket, and #239 – we were hoping, to complete the report this morning, to be able to:

(1) Filter the lists by ISP group, eg all MNOs (Vodafone, O2, Three, EE)

(2) Filter by Fixed line without BT-Strict (BT Light, Sky, TT, Virgin)

(3) Filter by MNOs + Fixed line without BT-Strict

(4) Filter the results above for .uk domains only

Is that possible at this stage? We may have a problem if not.

**Comment by dantheta** [comment]
I can switch the network filter to a set of checkboxes instead of
include/exclude links.  Is this needed for the lists summary page, the
list detail pages or both?

Ed has already created .uk versions of some of the lists, which can then
be filtered by ISP.

**Comment by JimKillock** [comment]
Checkboxes would work for sure.

.uk would still be very handy if even if it can’t be done today / right now.

**Comment by edjw** [comment]
The .uk lists I made were manually imported lists from Simon’s curated list of .uk sites.

They’re the top ones here: https://www.blocked.org.uk/lists <https://www.blocked.org.uk/lists>


–––––
Ed Johnson-Williams

**Comment by JimKillock** [comment]
Understood. I would still like to have the .uk filter though.

**Comment by dantheta** [comment]
Hmm, #242 already covers the TLD filter options.  I don't think there's anything else to add for this issue.
