### ISSUE TITLE
Merge "sites" and "lists" page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#245]
I think it would make sense to put the whole of the content on the lists page below the search on the https://www.blocked.org.uk/sites page.

The lists and the associated stats give a good idea of what kinds of things can be found.

**Comment by edjw** [comment]
Yes I agree that would be good

**Comment by dantheta** [comment]
This is done.  The network filtering on the savedsearch screen interacts slightly with the network dropdown in the search form, but this only affects administrators.

This is only because they started off using the same query string parameter - it's not a deliberate entanglement.
