### ISSUE TITLE
ISP Blocks by domain: add .com

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#247]
The set of tables here should include .com as we've tested a significant portion of that.

**Comment by edjw** [comment]
In this chart: https://www.blocked.org.uk/stats#ispblocks

This should say "ISP Blocks by top-level domain" not "ISP Blocks by domain" right?

**Comment by JimKillock** [comment]
I think this is done; could I request that the stats remove ISPs without filters in these lists? The graphs are hard to read with all of the blank ISP lines.

**Comment by dantheta** [comment]
zero-block entries have been removed from the ISP graphs, and they are now slightly taller to give more space to the axis labels.

**Comment by JimKillock** [comment]
Thanks Dan, is this counting copyright blocks perhaps? It looks that way as unfiltered networks are still being displayed.

If copyright blocks are included / counted, I would exclude those, as these stats are presented in the context of the filtering systems.

**Comment by dantheta** [comment]
Yes - I'm regenerating the domain stats now.

**Comment by JimKillock** [comment]
Hi Dan, the domain stats aren't looking right to me yet, so I'm reopening this.

**Comment by dantheta** [comment]
It does appear that we've had some parental-control blocks appearing sporadically on one or two of the unfiltered lines.  I'll update the selection criteria for the charts to stop those appearing.

**Comment by dantheta** [comment]
The graphs are regenerating now with new ISP selection active.
