### ISSUE TITLE
Report stats "Not only adult content is being blocked"

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#249]
The tables are here showing stats including BT Strict; this is different to the methodology we use in the report, so we need this to calculate for just fixed default lines + mobile lines.

Apols if this is a duplicate; I couldn't find the ticket I thought I'd raised yesterday.

**Comment by dantheta** [comment]
This should be done - yesterdays ticket was #246 

The first table was OK, the second was updated to exclude bt-strict.

**Comment by JimKillock** [comment]
Thanks Dan, yes, I forget that the initial list is still taking account of all ISPs, but that's harder to fix.
