### ISSUE TITLE
Bug: Front page stats at zero

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#253]
Some of the stats about reporting are showing a zero.

**Comment by dantheta** [comment]
Fixed

On 2 April 2019 11:06:58 BST, JimKillock <notifications@github.com> wrote:
>Some of the stats about reporting are showing a zero.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openrightsgroup/cmp-issues/issues/253

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
