### ISSUE TITLE
Leading spaces in site checking aren't being removed

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/cmp-issues#255]
If you type a space before the URL or you paste in a URL with a space before it into the Unblock your website form it goes like this below

![CleanShot 2019-06-03 at 10 21 39](https://user-images.githubusercontent.com/6547979/58791080-76e36900-85e9-11e9-8036-e4078fbea37d.gif)

We should probably strip spaces before they start being processed

**Comment by dantheta** [comment]
Added a whitespace strip before the frontend checks that the protocol is present.
