### ISSUE TITLE
Record checkbox set/cleared state explicitly

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#27]
The form on the front-page of the site has three checkboxes to opt into various email notifications:  allowcontact, subscribereports and joinlist. If the visitor sets these, their state is recorded in the FormSave table explicitly with an element in the JSON data blob, called e.g. 'allowcontact = yes'. If a checkbox is clear on submission, however, its state is not recorded. There is no equivalent 'allowcontact = no' entry in the JSON data.

Recording cleared checkboxes explicitly rather than implying their state from an absence of data would have two advantages:
1. Scripting actions based on the data becomes easier.
2. If the number of checkboxes changes in future we can distinguish in the data between "option didn't exist at the time" and "option wasn't selected."

**Comment by mkillock** [comment]
This should be working as desired now. Perhaps @dantheta can confirm that allowcontact is always being passed in as either yes or no?

**Comment by mkillock** [comment]
Along with the other two tick box options 'information' and 'joinlist'

**Comment by mkillock** [comment]
CORRECTION: The three tick box fields are

allowcontact    yes/no
subscribereports    yes/no
joinlist    yes/no

**Comment by graphiclunarkid** [comment]
I had a look at this on staging while I was fixing something else. By looking in the database I could see it wasn't working as expected however I think I've found the problem. In the part of the submitURL snippet where we build an array of fields to submit to the database I believe...

``` php
'additional_data' => http_build_query($_POST),
```

should be

``` php
'additional_data' => http_build_query($hook->getValues()),
```

Otherwise we're storing the original data that was POSTed to the script not the data that's been modified by the script itself.

I've tested this on stage.blocked and it worked so I've copied the change over to new.blocked. Does this seem OK to you?

**Comment by mkillock** [comment]
Sounds correct to me, I think I must have neglected to change that after copying the example code for submission on GitHub. May need to check what actually ends up in the API DB, though? Yes, $_POST will not have the 'no' for unticked options and the userEmail field and submittedURL fields would be missing, leaving only the hashed values.

**Comment by graphiclunarkid** [comment]
Here's an example of what ended up in the API DB:

```
4DRXNE97LE=http%3A%2F%2Fexample.com&category=Education&type=Static&content=Hacking+%28coding+and+computer+skills%29&information=Testing...&allowcontact=yes&SSQ97709WZ=richard%40openrightsgroup.org&url=&email=&joinlist=no&subscribereports=no&userEmail=richard%40openrightsgroup.org&domainToCheck=http%3A%2F%2Fexample.com
```

I'm now trying to do a bit of tidying up so that we don't store the same data against both the obfuscated and real field names!

**Comment by graphiclunarkid** [comment]
OK I've updated the snippet to remove the obfuscated fields from what gets stored in additional_data by setting them to null:

``` php
//Add corrected names back into Form Values...
$hook->setValue('userEmail',$userEmail);
$hook->setValue('domainToCheck',$domainToCheck);

//...and don't save the obfuscated or dummy ones
$hook->setValue('4DRXNE97LE', NULL);
$hook->setValue('SSQ97709WZ', NULL);
$hook->setValue('email', NULL);
$hook->setValue('url', NULL);
```

The database column contents look much cleaner now :smile:

```
category=Government&type=Blog&content=Campaigning&information=Testing+submission_info+field+clean-up&subscribereports=yes&joinlist=no&allowcontact=no&userEmail=richard%40openrightsgroup.org&domainToCheck=http%3A%2F%2Fexample.com
```

If you're happy with this then I think we can close this issue.
