### ISSUE TITLE
Results table column headings

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#28]
As a visitor viewing previous results for an ISP I want the results table to have column headings so that I know what each column means.

Current: 
![current-results-table](https://cloud.githubusercontent.com/assets/433456/3229673/feaebf42-f098-11e3-8619-e00e29e50b0c.png)

Desired:
![desired-results-table](https://cloud.githubusercontent.com/assets/433456/3229676/081f0ac8-f099-11e3-9e88-246ef732b983.png)

**Comment by mkillock** [comment]
ok, this can be achieved by creating a row for the table in the header template chunk. Have made an attempt. Perhaps @webal can improve if desired!

http://stage.blocked.org.uk/results.html?url=http://www.piratebay.se

(same will happen for submission success page)

**Comment by graphiclunarkid** [comment]
Looks good to me! :shipit:

**Comment by webal** [comment]
oops forgot that! I'll add it in

**Comment by webal** [comment]
changed them to <th> & finished
