### ISSUE TITLE
TalkTalk result is "OK" for non-existent domain

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#29]
Trying: to get a result for the non-existent domain http://stage.blocked.org.uk/results.html?url=http://not-a-real-domain-aerg4rhafsd.com

Expected: all probes return an error because the domain doesn't exist.

Actual: 
![talk-talk-ok](https://cloud.githubusercontent.com/assets/433456/3229866/cddce0a8-f09b-11e3-8529-96b3d3db5d5f.png)
TalkTalk seems to be special!

**Comment by graphiclunarkid** [comment]
Do TalkTalk use some kind of redirect to a search page for domains that don't have DNS entries?

**Comment by dantheta** [comment]
Yes, yes they do.  How irritating.

**Comment by NetworksAreMadeOfString** [comment]
Urggh, ISPs make me sad

**Comment by dantheta** [comment]
We can switch the probe VM to Google DNS (or any other public DNS).  We'll still get the parental control blocking, but we won't get the advert searches for unresolvable domains.

**Comment by dantheta** [comment]
It appears VirginMedia have one as well, but it only kicks in some of the time.

**Comment by graphiclunarkid** [comment]
I believe VirginMedia have a facility in the account admin interface to switch off the "feature" (I discovered this while staying with someone who uses them as their ISP). There might be a similar facility for TalkTalk. I can ask Alex B to check all the lines for this if that would be useful? I'm a bit wary of using third-party DNS as it's straying a bit from the default configurations experienced by most users. In some cases it might result in us bypassing a filter normal users would hit.

**Comment by dantheta** [comment]
Yes, I think you're right.  If Alex could take a look, that would be cool.

**Comment by graphiclunarkid** [comment]
Alternatively we could write a config-rule that detects these search screens and logs the result as "error" for our purposes. We could even confirm by using a separate query to our own DNS servers.

**Comment by dantheta** [comment]
That's true - I was considering a similar workaround for BT's one broken proxy server.  It's hard to know whether to try describing these workarounds as pure config, or just write the code and enable these workarounds from ISP config by name.  I don't think we really want a turing-complete configuration language! I'm leaning towards code enabled by config, I think.

**Comment by graphiclunarkid** [comment]
@dantheta Whatever works, I guess!

I have emailed Alex to ask if he can check the admin interfaces and switch off the "feature" where possible.

**Comment by graphiclunarkid** [comment]
Maybe we should raise new issues against our probe repositories to detect whether this "feature" is active on the connections under test? Otherwise our crowdsourced results might be polluted.

**Comment by dantheta** [comment]
We can add it to the rules config as "must-not-resolve".  That way the probes would refuse to start unless a centrally-controlled set of URLs were unresolveable.

I'll include http://www.badgersmakeexcellentpets.com/ by way of tribute :)

**Comment by graphiclunarkid** [comment]
I guess if we really cared we could detect "search" pages the same way we detect "blocked" pages. Then we could return a real "DNS resolution failed" response from the probe regardless of the fact that the ISP's resolvers don't behave themselves.

**Comment by dantheta** [comment]
We could also use a test against a second set of public nameservers to establish this.  That might be the quicker solution, if you're OK with that?  The main probe request would still be run using the ISP's own nameservers.

BTW - The TalkTalk setting change doesn't seem to have kicked in yet, we may need a router reboot for that.

**Comment by graphiclunarkid** [comment]
Using a second set of resolvers is fine with me. Perhaps we should do your 'must not resolve' check before enabling that feature, though, as it will be a waste of bandwidth and time for RFC-compliant ISPs.

Am I going to have to register that stupid domain now? :wink:

I'll ask Alex to reboot the TalkTalk router.

**Comment by graphiclunarkid** [comment]
Router rebooted. @dantheta says TalkTalk is now behaving properly. Do we want to raise a new feature-request for the optional checking via a second set of DNS servers if we suspect hijacking is taking place?

**Comment by dantheta** [comment]
Yep, I think we can close this one on the basis that it's fixed for the ORG landline ISPs.  It might be something to raise against the probes, so that they can check for this behaviour.
