### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#32]
Entries may include:
- What does an "OK" result mean?
- What does a "Blocked" result mean?
- What does an "Error" result mean?
- I can't access a site but the tool says it's OK. Why?
- I can access a site but the tool says it's blocked. Why?

**Comment by graphiclunarkid** [comment]
- My mobile network is FOO but the Android / Py / Ooni probe says it's BAR. Why?

**Comment by JimKillock** [comment]
Are we doing this for launch?

**Comment by JimKillock** [comment]
I think we should do this, as we may get quite a few enquiries at launch. We can have it started and add as we get new but likely to repeat questions.

**Comment by graphiclunarkid** [comment]
Q: What filtering settings are configured for each ISP and why

**Comment by graphiclunarkid** [comment]
Page added. Styling done.

**Comment by graphiclunarkid** [comment]
Content added. Could do with a review by @jimkillock and @pamcowburn.

**Comment by webal** [comment]
FYI I've updated the css file to make the questions stand out a bit better

**Comment by graphiclunarkid** [comment]
Thank you!
