### ISSUE TITLE
Review website copy post-migration

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#35]
Pam is going to review the site copy and make improvements where possible

**Comment by graphiclunarkid** [comment]
@pamcowburn: Can you explain why the community information no longer appears on the get-involved page (on the live server)? Is it moving to a new page perhaps?

References to the get-involved page across the rest of the site tend to assume this page is about how to become a tech-volunteer.

Since the project will be developed further after the launch of v2.1 I don't think we should omit information about how to volunteer. I'm hoping more people will want to get involved with the community on the back of the publicity we're anticipating!

**Comment by pamcowburn** [comment]
It hasn't been deleted, I was just moving the text around. I'm still in the middle of editing the site. I was going to see if that would fit better in the contact pages.

**Comment by graphiclunarkid** [comment]
@pamcowburn Ah, fair enough! Sorry - it looked like it was destined for the cutting-room floor for a minute ;-)

**Comment by pamcowburn** [comment]
Don't worry I have kept a copy of all the original text so my edits can be reversed if necessary!

**Comment by graphiclunarkid** [comment]
Perhaps the "future plans" section on the get involved page should move to live with the "how it works" section on the about page?

I don't think the community's collaboration methods are really "contact details". I think these need to be on the "get involved" page with the other information about the community. They're also duplicated on the "about" page at the moment.

**Comment by graphiclunarkid** [comment]
Can we review our use of language across the site? I think the following need looking at:
- Use of the words censored, blocked and filtered. Let's make sure we're consistent and it doesn't sound clumsy. If we're calling this censorship let's make it obvious.
- Use of the terms URL, site, page, website, etc.
- Remove any references to emailing results when they are ready: we're no longer building this feature).
- References to "Blocked!" in text rather than headings. (Do! we! really! want! The! Register! to! write! about! us! like! it! does! about! Yahoo!?) We've been referring to the site as blocked.org.uk and the project as "[the|ORG's] censorship monitoring project".
- Are we blaming the Government or ISPs for imposing filtering? We say "government censorship" on the personal stories page - is this accurate? Will writing to MPs be effective when it's ISPs who are imposing these filters "voluntarily"?

**Comment by graphiclunarkid** [comment]
I think we should get rid of the huge map on the contact page. Maybe that page's layout should be similar to that of the license page?

**Comment by pamcowburn** [comment]
I think OK to switch between censored, blocked and filtered as long as there is some consistency, otherwise it can be repetitive. The narrative should be that filters block sites, which leads to censorship.
I prefer using Blocked or the Blocked project rather than CMP. I think it's stronger.
I don't think I can change the form on the personal stories page.
I think the line is that the government is forcing/pressurising ISPs to promote filters.  Agree we need to make the MP action more specific or have an ISP action.

**Comment by graphiclunarkid** [comment]
- Agree on switching between synonyms - also I think your narrative that filters blocking sites results in censorship is great :)
- CMP is out, then, at least for use on the site (we may still refer to that in the technical community - off site).
- I've updated the form on the personal stories page - let me know if you want to make any further changes (or it's in the "tellstory" chunk, resource number 359, if you want to make them yourself).
- ISP action would be great but is too much to build right now. Let's review MP action with @edpw and @jimkillock when we can.

**Comment by graphiclunarkid** [comment]
To do list:
- [x] About page: Link to Error 451 site from about page (where we talk about court-ordered blocking)
- [x] About page: remove MP CTA box and replace with the Support the Blocked project and the bullets that appear lower down.
- [x] Newsletter sign-up CTA
- [ ] Contact page: remove map (having second thoughts about this now though!)
- [x] Contact page: remove community collaboration info.
- [x] Contact page: fix broken internal links.
- [x] Get involved page: solicit help with translating into other languages

**Comment by graphiclunarkid** [comment]
I have added a newsletter sign-up CTA to the about page (bottom right). It uses a new snippet based on @mkillock's additions to SubmitURL snippet for the same purpose. I have no idea if it works! If @JimKillock or @RuthC could check e-activist for a subscription this evening from bogus@richard-king-blocked-test.com (and then delete it, obviously) that would be great. Thanks!

**Comment by graphiclunarkid** [comment]
OK - I think everything that's been discussed is now implemented. Please do give the site a quick read-through when you get this as it's probable I've missed something. If you need me to do anything further please let me know.
