### ISSUE TITLE
Automate subscription to e-activist mailing list

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#38]
When a visitor ticks the box to subscribe to ORG's mailing list we want to subscribe them via e-activist automatically.

**Comment by mkillock** [comment]
I've written something on staging for this, in SubmitURL under the section titled "//SUBMIT EMAIL TO E-ACTIVIST AS NECESSARY" - I've commented out the line where the data is actually posted for now.

I checked the code by posting data to our url submission form, and it worked, so I changed the config to point to e-activist and have asked James to see if the registration is successful, not heard anything back yet.

**Comment by JimKillock** [comment]
We got a result for test@ but not forum@

**Comment by mkillock** [comment]
The code in SubmitURL on staging now automatically submits emails to EA ORG list when joinlist=checked. I've not copied to live.

Later enhancements can be to add full name/postcode to a form - some discussion first perhaps? Do we want to present yet another form with postcode and full name and the other fields? Or include these perhaps unnecessary items on the thank you page?

**Comment by graphiclunarkid** [comment]
Copied to live. Please can someone with access to e-activist test this is working from http//new.blocked.org.uk/ ?

@jimkillock, @ruthc

**Comment by graphiclunarkid** [comment]
Hi @jimkillock, @ruthc - is there any indication this is working? Have we had many sign-ups to the mailing list from Blocked since we launched the latter?

**Comment by graphiclunarkid** [comment]
Hi @jimkillock - please can you review whether this feature is working? If so, please can you close this issue? Thanks.

**Comment by graphiclunarkid** [comment]
I have now verified with Jim that this is working.
