### ISSUE TITLE
Create editable MODX templates

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#39]
The single template needs to be changed so that the content can be easily edited by MODX users. For instance the content areas, such as [[*content]] should be simple html without div structures so that WYSYWG editors can write content. As a first step I've moved most of the html into chunks on the live server. This can be rearranged if it seems confusing tho.

**Comment by graphiclunarkid** [comment]
Omnomnomnom.... ;-)

**Comment by JimKillock** [comment]
This is all done except for the personal stories page, which is a bit more complicated and I may need help with. I've raised a separate issue of that.
