### ISSUE TITLE
ORG mobile probe set up

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#42]
Set up the ORG mobile probes with mobile SIMs from Vodafone / EE / O2 / Three

**Comment by JimKillock** [comment]
Current status of SIMs: O2 arrived, EE and Three on order, Vodafone awaiting paperwork from Simon to return to Vodafone

**Comment by JimKillock** [comment]
Three now arrived; paperwork sent to Vodafone.

**Comment by JimKillock** [comment]
Vodafone SIM now ordered and on the way to the office

**Comment by graphiclunarkid** [comment]
@gwire has set up the Raspberry Pis are set up in the office, installed OSs on them, and routed them to the outside world via a new router. Three out of the four have mobile dongles installed and working: O2, Vodafone and EE. We're waiting for the Three SIM, which I understand @jimkillock has.

There is a routing-table issue to overcome because the Pis have more than one network interface. @dantheta has some experience of configuring either iptables or the routing tables to deal with this.

The connection to the Pis seems intermittent. It was working late on Friday and early on Saturday but has not worked since. Perhaps this is something to do with the new router?

**Comment by dantheta** [comment]
Vodafone, O2 and EE are all up and running.

**Comment by JimKillock** [comment]
the Three SIM is now activated and installed in the RPi if @dantheta wants to give it a go.

**Comment by dantheta** [comment]
Hiya - 

I'm having a bit of trouble getting sakis to start the 3g connection. 
Three's site says that the APN is "three.co.uk" (with no username or
password), but sakis reports an SIM error while checking for a PIN ...

The eth0 routing fix is installed on that pi, so it's fine for the 3G link
to come up and down.  Does anyone have any ideas?

Daniel.

**Comment by JimKillock** [comment]
You8 could try navigating to 

three.co.uk/my3

and see what it says. Three assured me it was working but they could be wrong. Alternatively we could try to SIM on a computer here to make sure it’s working.

**Comment by dantheta** [comment]
I've moved the 3g connection on O2 from sakis to wvdial (which seems to be a bit more stable).

**Comment by graphiclunarkid** [comment]
What is the current status of the 3 SIM? Are we still using @dantheta's (for which he is paying)? Or have we sorted out default filtering on ORG's contract SIM now?

The EE probe seems (subjectively) to be throwing a lot of errors. Is that still to do with a lack of signal in the office or something else?

**Comment by dantheta** [comment]
The 3 sim never developed filters, sadly.  The system is still using my PAYG SIM, but it's not expensive :)

The EE probe has had a lot of connection problems (as have all three of the SIMs on the mobile probes) - but they have been more frequent and of longer durations.

All three of those probes (vodafone,three & O2) currently need a kick.  I think ideally disconnecting the PIs from power and/or disconnecting & reconnecting the huawei dongles.  Sakis is currently unable to get the mobile connection started on them.

**Comment by dantheta** [comment]
Oh - EE  has come back.

O2 gives a "failed to connect" error, and vodafone is returning "Modem unable to register a network.".

If might be worth checking the vodafone one in a laptop.

**Comment by mkillock** [comment]
Are the Pis getting enough power? Mine used to just crash every so often until I got a power supply that gives more amps. Also I read somewhere that there was a power issue on the USB ports on some models, though that was probably older versions

**Comment by dantheta** [comment]
The pi's seem stable enough, and the mobile network dongles are connected through a powered hub, so I think that's OK.   When I was trying a Pi with a huawei dongle connected directly (drawing power through the Pi) it would crash after less than an hour.

**Comment by dantheta** [comment]
We're still having trouble with the Vodafone and O2 probes - I can't get them to connect to the mobile networks at all any more.  If there's time, would it be possible to get them connected to a laptop for testing?

I've reinstated the PAYG probes temporarily on those two networks to get the queues down.

**Comment by JimKillock** [comment]
Sure, I can take a look on Tuesday. I guess ORG also needs to replace the EE Sim with a censored EE mobile SIM.

**Comment by dantheta** [comment]
The EE sim is OK, it's Three that doesn't have any filtering :)

**Comment by dantheta** [comment]
The EE sim has just rolled over to a new month of transfer allocation, but the signal is rather low and I can't get a stable connection to the mobile network.  I've rolled out a change in OrgProbe which should save some bandwidth, so hopefully this month we won't go over the 1Gb.  We should now be able to check at least 115,000 pages with 1GB of transfer.
