### ISSUE TITLE
Image(s) for social shares

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#43]
We could do with a square version of the blocked logo, adapted for the pages for social shares, e.g. featuring a word for the each page such as "check URL" / "Help"  / "Stories" etc

**Comment by webal** [comment]
do you mean something along these lines? I'll tidy it up a bit, but I don't think it'll work as a square.

https://dl.dropboxusercontent.com/u/12755204/blocked-org-uk/gfx/blocked-check-urll.png

**Comment by graphiclunarkid** [comment]
Maybe we need an icon to go with the logo. A no-entry sign, but coloured black, is what I thought of immediately. No doubt others will have better ideas.

**Comment by webal** [comment]
something like this maybe? http://www.shutterstock.com/pic-79140361/stock-vector-stop-hand.html?src=6Q90Qt5aGPfnLEkQacICPg-1-34

**Comment by graphiclunarkid** [comment]
I like that @webal :)

Reading this again, I'm not sure I've really understood what @JimKillock was after, I'm afraid. Did you mean images rather than text for the menu options, Jim, or a button we can use on other sites to link people through to blocked.org.uk?

:confused:

**Comment by JimKillock** [comment]
@webal That is what I need yes, thank you (maybe a little lighter text on the "check URL bit") The image needs to be about 800px square IIRC  @graphiclunarkid This is to display on Twitter cards / FB previews etc., it lives in the meta tags for them to pick up. See for instance https://en.wikipedia.org/wiki/Facebook_Platform#Open_Graph_protocol

**Comment by JimKillock** [comment]
Ping on this in case we can fix it before launch. @webal you can just send me a larger version of the blocked logo, being about 600px wide (whatever height)

**Comment by webal** [comment]
I've added it to the repo here: https://github.com/openrightsgroup/blocked-org-uk/tree/5ae567de5d4af5f1596d4602ebec516f4c0e447f/gfx

Sorry haven't had a chance to do much this weekend, I'll be clearing up what I can over the weekend.

**Comment by JimKillock** [comment]
Great, that's all done. I've added the images for each social share, as well as implemented Twitter cards / OpenSocialGraph
