### ISSUE TITLE
BT probe errors

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/cmp-issues#44]
When the OrgProbe requests a page from a blocked site on BT Internet, there is a 25% chance that the probe will see a 403 forbidden response in place of the BT Parental Controls page.

This is because of a misconfiguration on one of the four proxy servers that blocked sites are directed to by BT.

This may have to be worked around in code.

To test, repeatedly run:

```
curl http://www.reddit.com/r/nfsw
```

Note the responses and the addresses that reddit.com resolves to.

```
# curl -v http://www.reddit.com/r/nfsw
* About to connect() to www.reddit.com port 80 (#0)
*   Trying 213.120.234.109...
* connected
* Connected to www.reddit.com (213.120.234.109) port 80 (#0)
> GET /r/nfsw HTTP/1.1
> User-Agent: curl/7.26.0
> Host: www.reddit.com
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 403 Forbidden
< Connection: close
< 
* Closing connection #0
# curl -v http://www.reddit.com/r/nfsw
* About to connect() to www.reddit.com port 80 (#0)
*   Trying 213.120.234.146...
* connected
* Connected to www.reddit.com (213.120.234.146) port 80 (#0)
> GET /r/nfsw HTTP/1.1
> User-Agent: curl/7.26.0
> Host: www.reddit.com
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 302 Found
< Location: http://blockpage.bt.com/pcstaticpage/blocked.html?policy=Z2xvYmFsLW1vZGVyYXRlLWQ2MzJjYmU0LTg1NWUtNDlhMC1iMTE3LTI1N2EyNmU1MDVhOA==;&view=ZDYzMmNiZTQtODU1ZS00OWEwLWIxMTctMjU3YTI2ZTUwNWE4;&list=BT-Moderate&originalUrl=aHR0cDovL3d3dy5yZWRkaXQuY29tL3IvbmZzdw==
< Connection: close
< 
* Closing connection #0
```

(hopefully the markup has worked)

**Comment by graphiclunarkid** [comment]
Can we work around it in code for now?

I am also happy to try reporting the problem to someone at BT if we can figure out an appropriate contact for talking to them about their filters.

**Comment by dantheta** [comment]
Yep, I'll be working on it this weekend.

**Comment by dantheta** [comment]
I've retested the case above, and the .109 proxy is now returning results consistent with the others!  Tested with a range of parental-controlled URLs.

Closing the ticket.
