### ISSUE TITLE
Logo overlaps menu at some resolutions

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#48]
At some browser widths the new BLOCKED logo overlaps with the menu items.

Expected: clear space around the logo and menu

Got:

![logo-menu-medium](https://cloud.githubusercontent.com/assets/433456/3354853/43e7aa04-faaa-11e3-8a2f-502239767d02.png)
![logo-menu-small](https://cloud.githubusercontent.com/assets/433456/3354854/494dd07c-faaa-11e3-99f7-0b06587c80d6.png)

Also: can the menu background colour at these widths be changed? If so, I think white be better than grey, as that would be consistent with the menu colour when the browser window is wider.

**Comment by webal** [comment]
not sure what happened there the responsive nav wasn't working properly, Updating bootstrap seemed to fix it.

I had to switch to the cdn for bootstrap though as Modx wouldn't allow me to upload the various font files.

All fixed now if someone wants to check

**Comment by graphiclunarkid** [comment]
Just checked and it works fine for me. Thanks!
