### ISSUE TITLE
Contacts record with null email address created if no contact check-boxes are set

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#49]
Trying: to submit the form on the results page without changing any of the fields (i.e. form is blank)
Expected: validation error
Got: Form is submitted successfully; database badness happens.

The front-end form validation only validates the email address field if one of the three checkboxes is set (allowcontact, subscribereports or joinlist). If all three are cleared, and the email field is empty, the form can be submitted successfully. The API then creates a request record as normal, which is fine, but it also creates a contact record for email address = NULL. This should fail but for some reason it succeeds. Subsequently, all requests with null email address fields get associated with this contact record.

I suspect email should not be a nullable field in the contacts table. Even if it were to be nullable we should be detecting that the field is empty and not trying to create a contact for a null email address!

**Comment by dantheta** [comment]
Ah - I don't think the email was null in the database (the column has not null declared on it).  The email address field is empty ( '' ) on one record though.  The patch in the pull request will handle it though.

**Comment by graphiclunarkid** [comment]
Thanks Dan - yeah, I thought that column was NN, but I raised the bug before I checked the DB schema ;-) Just fixing up the patch now based on your comment.
