### ISSUE TITLE
Install new TLS certificates for dev-censor-1

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#5]
OpenSSL on dev-censor-1 has been upgraded to a version patched against Heartbleed. I believe Lee has a new SSL cert ready to go. It just needs to be installed.

**Comment by graphiclunarkid** [comment]
I received the following from Lee this afternoon:

```
I’ve uploaded the following to dev-censor-1 - a wildcard for *.blocked.org.uk

/etc/pki/tls/private/blocked-2014.key
/etc/pki/tls/certs/blocked-2014.crt
/etc/pki/tls/certs/blocked-ca.crt

But I can’t do anything more at this time because:

1) there’s one external IP address on the box and it’s being used for “api.bowlderize.co.uk”?
2) CentOS(?) is a mystery box to me and I don’t know what group the keys in /etc/pki/tls/private should have - apache I assume.

But I assume Gareth can take control?
```

AFAIK api.bowlderize.co.uk is only used by https://github.com/openrightsgroup/Android-Probe. The Android probe isn't working at the moment because we've made breaking changes to the API. Since that probe needs some work to upgrade it to API v1.2 anyway, we could at the same time make it talk to api.blocked.org.uk rather than api.bowlderise.co.uk, so I don't think it's a problem to kill off the latter at this stage. That would let us update the TLS certificates and start using TLS for the main API.

Any thoughts @dantheta, @webal, @NetworksAreMadeOfString?

**Comment by EvelynSubarrow** [comment]
I vote for its swift death.

2014-05-16 17:57 GMT+01:00 Richard King notifications@github.com:

> Received the following from Lee this afternoon:
> 
> I’ve uploaded the following to dev-censor-1 - a wildcard for *.blocked.org.uk
> 
> /etc/pki/tls/private/blocked-2014.key
> /etc/pki/tls/certs/blocked-2014.crt
> /etc/pki/tls/certs/blocked-ca.crt
> 
> But I can’t do anything more at this time because:
> 
> 1) there’s one external IP address on the box and it’s being used for “api.bowlderize.co.uk”?
> 2) CentOS(?) is a mystery box to me and I don’t know what group the keys in /etc/pki/tls/private should have - apache I assume.
> 
> But I assume @NetworksAreMadeOfString can take control?
> 
> AFAIK api.bowlderize.co.uk is only used by
> https://github.com/openrightsgroup/Android-Probe. The Android probe isn't
> working at the moment because we've made breaking changes to the API. Since
> that probe needs some work to upgrade it to API v1.2 anyway, we could at
> the same time make it talk to api.blocked.org.uk rather than
> api.bowlderise.co.uk, so I don't think it's a problem to kill off the
> latter at this stage. That would let us update the TLS certificates and
> start using TLS for the main API.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openrightsgroup/cmp-issues/issues/5#issuecomment-43354538
> .

## 

_kuta li wudema pinume!_

_Information wants to be free!_

_@korikisulda https://github.com/korikisulda/
https://github.com/korikisulda/_

_時は私達の敵です_

**Comment by dantheta** [comment]
The pyprobe also uses it, but is easily amended.  The 1.1 api should still work, but it has had no requests in quite a while. I think it should be safe to retire the certificate.  I'm happy to move the files into place, I know redhat/centos very well.

**Comment by dantheta** [comment]
I've checked the PHP example client, and it appears that the inbuilt https protocol handler that PHP uses does not perform certificate validation.  This is probably something we'll want to fix, but it does also mean that we're free to change the certificate without it breaking the PHP code in the frontend.

I'll switch over the certs on Sunday and test.

**Comment by dantheta** [comment]
The new certs are live now.  Permissions are good.

The existing api connection on stage.blocked.org.uk is still good, since there's no certificate verification going on there.
