### ISSUE TITLE
New page: thanks for submitting your information

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#53]
This is the page to which the form on the results page redirects when submitted. Necessary because we moved most form elements to the results page (#36).

https://new.blocked.org.uk/thanks-for-submitting-your-information

(This is page ID 7482 in the new.blocked modx instance)

Needs:
- Page content
- Styling
- Navigation

Suggestion:
# Thanks!

If you signed up to receive emails from us please check your inbox for our confirmation message. Watch out - it might end up in your spam or junk folder. Click the link to confirm your address.
## Where do you want to go now?
- Share on social media
- Back to the results
- Check a new URL
- Join ORG

**Comment by webal** [comment]
I can have a crack at that tomorrow night

**Comment by graphiclunarkid** [comment]
Basic page layout and content complete. Needs social sharing buttons but will do this as part of openrightsgroup/blocked-org-uk#30.
