### ISSUE TITLE
Provide % blocks per ISP

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#54]
@pamcowburn would like results per ISP. This would ideally be against a known data set, e.g. Alexa top 100,000 to give it verifiability. This could be displayed on the site (ideally) or just reported back to us. If we can get it soon, we can use for the media launch.

**Comment by dantheta** [comment]
That's no problem.  What format would you like (Excel, Openoffice)?

**Comment by JimKillock** [comment]
Either, Open Office is what we use day to day - thanks!

**Comment by dantheta** [comment]
I've sent the URL dataset and the network summary to you and Pam.

**Comment by JimKillock** [comment]
That's great @dantheta - there's lot of useful info there! Could you (or someone) help us process the data into some simple stats? Ie total instances of blocks per ISP - I'm not great with spreadsheets!

**Comment by JimKillock** [comment]
BTW eyeballing the list gives lots of crazy block examples …

**Comment by dantheta** [comment]
Yep, I'll add some percentages to the summary sheet and resend - it'll be a little bit later today, though.  Hope that's OK.

**Comment by JimKillock** [comment]
That's great Dan. I'll leave the ticket open as a possible enhancement. Although we probably need a bigger conversation about where the next steps in terms of stats, public info, queries to the DB should be :)

**Comment by graphiclunarkid** [comment]
That "bigger conversation" is issue #31.
