### ISSUE TITLE
Long domain-names don't wrap results page, causing layout issues

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#57]
![screenshot from 2014-06-30 17 10 54](https://cloud.githubusercontent.com/assets/433456/3431269/08470840-0069-11e4-89e5-ebc652f88f2e.png)

**Comment by graphiclunarkid** [comment]
Ironically this looks better at lower browser widths because Bootstrap moves columns to be rows so the lengthy URL doesn't overlap the content in columns to the right!

**Comment by mkillock** [comment]
I can add a space in every so often? Bear in mind that the page title uses the same placeholder so I can't put BR tags in there.

**Comment by mkillock** [comment]
Added $url = chunk_split($url, 40, ' '); to snippet, so every 40 chars gets a space. The gap can be adjusted very easily if required.

**Comment by mkillock** [comment]
Oh, just noticed that is the thankyou page, will need to add to another snippet too

**Comment by mkillock** [comment]
Have added to GetURLHistory snippet in various places too. We may want to adjust the distance between gaps depending on where the url is displayed, which is possible

**Comment by mkillock** [comment]
Closing - reopen if the gaps are incorrect!

**Comment by graphiclunarkid** [comment]
Still not working for me on /thankyou page. Tested on new.blocked and stage.blocked. Works on the /results?url=http://somethingridiculouslylong.com page though.

I think a better solution might be something like:

``` php
$urlstring = (strlen($url) > 40) ? substr($url,0,37).'...' : $url;
```

Then we can use:

``` html
<a href="$url" title="$url">$urlstring</a>
```

This would truncate the URL displayed on the screen to 40 characters, trailing off with "..." if truncated so people can see what we did. Hovering over the URL would display the full link as a tooltip.

**Comment by mkillock** [comment]
OK, will check this out later (approx 8pm)

**Comment by mkillock** [comment]
Looking at this now

**Comment by mkillock** [comment]
OK, done! Perhaps @graphiclunarkid can check?

New snippet called GetUrlFromLink running in results and thankyou page chunks that
1. returns full url in [[!+fi.domainToCheck]](to remain forward compatibility for combining the two pages into one later)
2, returns shortened url in [[!+ShortenedURL]]

NOTES from snippet:
// NOTE: this snippet can be called on the thankyou page and the results page. See respective Chunks
// Situations that must be covered:
// 1. Thankyou page visited without first submitting url. 
//    - FormItRetriever will return [[!+fi.domainToCheck]] as blank, $_GET['url'] will blank
//    - Action: Do nothing, let GetURLHistory snippet redirect to home page
// 2. Results page visited without providing a url.
//    - FormItRetriever not called so [[!+fi.domainToCheck]] will be blank, $_GET['url'] will blank
//    - Action: Do nothing, let GetURLHistory snippet redirect to home page
// 3. Thankyou page visited after submitting url.
//    - FormItRetriever will return [[!+fi.domainToCheck]] with url, $_GET['url'] will be blank
//    - Action: leave [[!+fi.domainToCheck]] alone, return [[!+ShortenedURL]]
// 4. Results page visited with valid url in URI
//    - FormItRetriever not called so [[!+fi.domainToCheck]] will be blank, $_GET['url'] has url
//    - Action: Set [[!+fi.domainToCheck]] to url, return [[+ShortenedURL]]

**Comment by graphiclunarkid** [comment]
I think the snippet is spot-on, thanks!

I've made a few changes to the layout of the pages, notably:
- Move the URL to a smaller heading below the main heading to fit in more characters.
- Set title="[[!+fi.domainToCheck]]" on the HTML elements containing [[!+ShortenedURL]] so that hovering over them displays as much of the full URL as possible in a tooltip.
- Avoided using the URL text where we don't need to (e.g. in the permalink paragraph).

I've checked the 40 character length across all the different bootstrap page-widths and it seems just about perfectly tuned :-) Maybe a little short for the full-width version but never mind.

I thought it'd be nice to display the full URL at least once on the site. I tried adding a new row above Results / Tell Us More, then moving the URL from below the Results heading into this row, however my exceedingly long URL just overflowed beyond the right hand edge of the screen. It looked a bit naff but if someone with more l33t skillz were to have a go it might work...

Still to do: replicate these changes to the static results page.

**Comment by graphiclunarkid** [comment]
Static results page now updated.

**Comment by graphiclunarkid** [comment]
Assigning back to @mkillock for a final check that I haven't done anything stupid - otherwise I think we can close this :)

**Comment by mkillock** [comment]
Looks fine! This snippet should enable us to merge the two chunks as one now - to save duplicating the content. Both FormItRetriever and GetUrlFromLink (in that order) will need to be called in the combined chunk, but it should work
