### ISSUE TITLE
URLs with trailing '/' treated as different sites to those without

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#58]
Split out from original discussion in #12

Trying: to visit the results page for a website.
Expected: requesting any of the following URLs gives the same results page 

https://new.blocked.org.uk/results?url=https://richardskingdom.net
https://new.blocked.org.uk/results?url=https%3A%2F%2Frichardskingdom.net
https://new.blocked.org.uk/results?url=https://richardskingdom.net/
https://new.blocked.org.uk/results?url=https%3A%2F%2Frichardskingdom.net%2F

Got: URLs ending in a forward-slash '/' character are treated as being different than those without:

https://new.blocked.org.uk/results?url=https://richardskingdom.net

gives different results to:

https://new.blocked.org.uk/results?url=https://richardskingdom.net/

**Comment by dantheta** [comment]
The API has a URL normalization function which can fold these two cases together.  I think that's probably a pretty good place to take care of it.  Does that sound OK to you?

**Comment by graphiclunarkid** [comment]
Yes, that makes sense. I did wonder whether it might be something we needed to tackle in the SubmitURL snippet (which deals with missing http:// prefixes) but your idea sounds better.

**Comment by dantheta** [comment]
I've just checked, and it's a pretty straightforward (with some data cleanup to follow).  Do you prefer the bare-domain URLs with or without a trailing slash?

**Comment by graphiclunarkid** [comment]
My opinion is that we should remove the trailing slash. That might be because I've just been looking at ways to prevent long URLs from screwing up the results page presentation though :wink:

**Comment by dantheta** [comment]
The test cases above all check out.  Now for the fun part - folding together all of the previous results for the URLs that have been folded together ...

**Comment by dantheta** [comment]
This seems to be working correctly.  There are 70 URLs where we have a trailing-slash and a no-trailing slash version of the URL, though not all of those are bare domain URLs.  

61 URLs have been folded together.  Job done!
