### ISSUE TITLE
Some TLS sites time out too quickly

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#60]
I think some sites served over TLS are taking longer than we expect to respond. The results then appear as 'timeout'. I'm not sure if the probes give up, or if this is reported by the API somehow, because refreshing a query for such a site sometimes returns more results for more ISPs.

Example: my blog is only available over TLS. Further, it uses encryption algorithms that support perfect-forward secrecy by default, the disadvantage of which is slower loading times because key exchange takes longer.

So visiting http://richardskingdom.net/ first does a 301 redirect to https://richardskingdom.net/ and then initiates TLS key-generation for some algorithm that takes a while to complete (a few seconds).

Is there anything we can do to increase the timeout for sites that we detect are doing something similar? It would be nice not to slow down checks overall - but maybe we should revise our assumptions about how long the average site will take to respond?

**Comment by dantheta** [comment]
Yep, we can enable different timeouts for different transports.  I'll open an issue on the probe repository to remind me.  If we need to increase the number of workers because some of them are blocked on slower network operations, that's absolutely fine - it's part of the design.

**Comment by dantheta** [comment]
I've double-checked the configuration, and the default timeout on the probes is actually 5 seconds across the board.  It's quite probable that in some cases (mobile networks especially) this isn't enough.

I'll run some stats on our results for timeout responses, and we can perhaps increase the timeout value on the mobile probes to 8 or 10 seconds.  We can increase the number of probe processes to compensate for the drop in throughput, we've got plenty of memory there.

**Comment by graphiclunarkid** [comment]
Did we ever resolve this @dantheta? I feel like your recent work might have made this question obsolete. If so, please would you close it? Ta.

**Comment by dantheta** [comment]
Yep.  The connection timeout is still 5 seconds, but we have improved the reporting of SSL errors.  I think we're covered.
