### ISSUE TITLE
URL shorteners

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#61]
When someone submits a URL from a link shortener such as tinyurl.com, bit.ly or t.co, are we interested in whether the short-link is censored or the page to which it redirects?

It would be interesting to investigate whether URL shorteners themselves engage in censorship - but that's not the current focus of this project. Maybe we should consider recognising shortner domains and dereference such links to their target URLs before passing them to the probes for testing?

**Comment by dantheta** [comment]
At the moment, the probes follow the redirects from the shortened URLs.  If the ISP decides to block that, then we record it as a block against the original shortened URL.  We could decide to record it as a block against both the shortened URL, the target URL (and any intermediate URL if there's a chain of URL shorteners at work), but it would require a change to the response submission part of the API.

**Comment by graphiclunarkid** [comment]
Awesome! I don't think any changes are necessary in that case. It sounds like we're treating URL shorteners as being transparent unless they're censored explicitly: so normally, submitting a shortened URL will cause its target to be tested, and the results for the full URL being reported.
