### ISSUE TITLE
Only update last blocked if blank?

### ISSUE THREAD

**Issue by mkillock** [openrightsgroup/cmp-issues#62]
At the moment, each time we run the probes on a URL it updates the last blocked entry, so essentially most of the time we're presenting the same datetime in two columns. Would it be better to not update this column unless it is (a) null, (b) it's just been checked and found to be blocked?

This would mean that we have a record of when we first discovered it was blocked, and we'd have two different dates when something is still blocked.

I may have misunderstood how that field is stored?

**Comment by dantheta** [comment]
That field isn't really stored - the date of the last test and result is stored, and when the URL status for each ISP is looked up, it also looks up the last date where the status was 'blocked'.  You're right though: in the instance where a fresh 'blocked' result has been obtained, the last blocked time will always be the same as the last test time.  I can easily change it to return the earliest timestamp of a blocked result though.  
For correctness, I'd want to return that as a new element in the json stanza, so we've got "first_blocked_timestamp" and "last_blocked_timestamp".  The frontend could then display something appropriate depending on the result as a whole.

**Comment by mkillock** [comment]
Ah, right, I thought I might have misunderstood the DB design. I'm in favour of the new element in the JSON - sounds fine to me, but it's only worthwhile if there is general agreement that we should show the "first_blocked_timestamp" in the 4th column of the results, or add a 5th column.

Anybody got any opinions?

**Comment by dantheta** [comment]
I think first_blocked_timestamp is more useful than last_blocked_timestamp in general:

If a URL is currently blocked, last_blocked_timestamp == now, first_blocked_timestamp <= now ; (for URLs with no test history, first_blocked_timestamp == last_blocked_timestamp)
if a URL has previously been blocked and is currently OK, last_blocked_timestamp < now and first_blocked_timestamp <= last_blocked_timestamp; (both fields are useful in this case).

Getting first_block as well as last_block isn't very expensive in database terms, so I'm happy to add the element to the JSON and you can experiment with it.

**Comment by graphiclunarkid** [comment]
If it doesn't cost anything to add the element to the API response then I say we should do it. Clients can then decide for themselves what (if anything) to do with it. We may choose to build a separate "detailed results" page, for example, that shows the entire blocking history for a URL on a single ISP. It could be reached by clicking the row corresponding to that ISP in the existing results table. (There are probably better ways, though, and that was just an example not a feature request!)

**Comment by dantheta** [comment]
Tested and deployed.
