### ISSUE TITLE
Ask visitors whether they think a URL should be blocked

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#63]
Javier has suggested on the mailing list that we should be asking people to say whether they think a site should be blocked:

"On the classification form https://www.blocked.org.uk/thankyou I think the first question should be, should this site be blocked? Yes or No.

"The system assumes that the site is incorrectly blocked and goes straight into categories but what if the site is less clear cut?"

**Comment by dantheta** [comment]
The wording for the question is going to be quite important; we can generally assume that a proportion of the audience is opposed to web blocking in general, so asking if a site should be blocked without providing any other context is likely to predispose a participant to answering "no".

We will soon be able to display the DMOZ category (and/or the block list category extracted from the ISP's response page).  In this context, we can show the site URL, a DMOZ/ISP category (e.g. Gun Violence), and then ask the question "Is this block an error (y/n)".  For a site that does not relate to guns, the answer would most definitely be "yes".

**Comment by JimKillock** [comment]
Yes, error is right. Maybe we could provide a bit more info / help users via a tool tip or similar when we get to building the front end.

**Comment by dantheta** [comment]
This should be ready for implementation - at the moment, we have a set of questions that are shown on the results page, and the form contents are fed to the API.  Adding the "Is this block an error" question there will work fine, and pass the result to the API for storage.  I'm going to be making some changes in the backend to store these form submissions in a more reportable form.

If frontend devs would like to make a start on adding this field, they should have everything they need.

**Comment by dantheta** [comment]
I've added the form element with the text "Has this site been blocked in error?", with the options Yes, No, Not sure and Not Applicable.  Some explanatory text would definitely help.

**Comment by dantheta** [comment]
Done some time ago.
