### ISSUE TITLE
4xx Error codes from API

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/cmp-issues#69]
I've seen a handful of 400/404 errors from the frontend to the backend API.  Are appropriate people aware of the issue on the other end?

(I've snipped out the arguments - if germane let me know and I will add.)

```
[2014-07-02 18:42:30] PHP warning: file_get_contents(https://api.bowdlerize.co.uk/1.2/status/url?[...]): failed to open stream: HTTP request failed! HTTP/1.0 400 Bad Request

[2014-07-02 18:48:10] PHP warning: file_get_contents(https://api.bowdlerize.co.uk/1.2/status/url?[...]): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
```

**Comment by NetworksAreMadeOfString** [comment]
That URL should be changed to api.blocked.org.uk ASAP

**Comment by gwire** [comment]
```
--- cmpconfig.php.prev  2014-05-28 12:17:29.000000000 +0100
+++ cmpconfig.php   2014-07-02 19:21:51.000000000 +0100
@@ -1,3 +1,3 @@
 <?php
-$cmpAPI = "https://api.bowdlerize.co.uk/1.2"; // proper URL
+$cmpAPI = "https://api.blocked.org.uk/1.2"; // proper URL
```

**Comment by gwire** [comment]
```
[2014-07-02 19:25:09]  PHP warning: file_get_contents(https://api.blocked.org.uk/1.2/status/url?[...]]): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
```

**Comment by mkillock** [comment]
They both point to the same IP, so it could be API call overload?

matt@juno ~ $ host api.bowdlerize.co.uk
api.bowdlerize.co.uk has address 213.138.109.226
api.bowdlerize.co.uk has IPv6 address 2001:41c8:51:4e2:feff:ff:fe00:30ff
matt@juno ~ $ host api.blocked.org.uk
api.blocked.org.uk is an alias for stage.blocked.org.uk.
stage.blocked.org.uk has address 213.138.109.226

**Comment by NetworksAreMadeOfString** [comment]
@mkillock I know but the SSL would be wrong which is bad :)

@gwire 404 could be legit if we're querying for the status of a URL that hasn't been submitted, try submitting it again and see if you still get a 404.

**Comment by gwire** [comment]
API response to call overload should probably be 
- 503 Service Unavailable (for a server issue)
  or maybe something like 
- 429 Too Many Requests (if the client is being excessive)

**Comment by gwire** [comment]
```
url=http%3A%2F%2F+img+src%3Dx+ONERROR%3DALERT+1+%3E
```

Ok, looks like at least one of those is someone checking for XSS.

**Comment by NetworksAreMadeOfString** [comment]
Yeah @graphiclunarkid just posted to tech-vols about it.

htmlentities() all the things! ;)

**Comment by gwire** [comment]
```
url=http%3A%2F%2Fhttp%3Areddit.com
```

resulted in a 400 - i.e. "http://http:reddit.com"

**Comment by NetworksAreMadeOfString** [comment]
Well that's correct IMHO (granted it should never have got through the normalisation process)

**Comment by dantheta** [comment]
The XSS one is a valid URL, The encoding of the url argument is just fine.

The API will issue a 400 error for the http://http:reddit.com example, I think (invalid request).

If you're using the static results page to look for results for a URL that hasn't been submitted, the API will send back a 404.  The static results page doesn't submit the URL, so it's quite possible it won't be found.

When you check the API call URL with curl, there's reasonably helpful JSON text describing the error.

I don't think the API has been overloaded - there have been no system load warnings, and the results queue has held at 0 (>0 means the database isn't keeping up).

**Comment by dantheta** [comment]
I've reviewed the logs, and the 400 and 40x responses were the result of RESTish status code responses to invalid input data or absent DB records.  Is it OK to close this issue?
