### ISSUE TITLE
Add Bytemark and AAISP info

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#7]

**Comment by graphiclunarkid** [comment]
Please can you fling me contact details for someone at Bytemark who can give us logos and text for this? I'm already in contact with AAISP so I can enquire there myself.

Do we want this on a separate "sponsors" page? In the site header or footer? Somewhere else?

**Comment by JimKillock** [comment]
Done!

**Comment by graphiclunarkid** [comment]
Thanks. I propose we add the sponsor information to the page footer so that it appears regardless of the page on which visitors land. Does that sound like a good idea? If so we can do this as part of openrightsgroup/blocked-org-uk#21

**Comment by graphiclunarkid** [comment]
Bytemark info here: http://www.bytemark.co.uk/company/spread_the_word
