### ISSUE TITLE
Regular CSV data dumps

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#70]
At the moment we have a static dump of the database contents from just before we launched. It'd be nice to refresh this on a schedule, say nightly, so that people could download up-to-date data.

**Comment by dantheta** [comment]
Hi - I've written the export script and schedule.  Are these headings OK (both in terms of analytical utility, and probe owner privacy?):

'URL','URL Submission Timestamp','Network Name','Filter Level','Status','Result Timestamp','HTTP Status','Probe Config'

Probe config is the version number of the rules file from the API that was used to process the response.

**Comment by dantheta** [comment]
Also, would the URL http://api.blocked.org.uk/data/export.[datecode].csv.gz be OK, or would you prefer that it lives on the www site?  If the latter, we'll need to sort out a means of copying the file there (perhaps key-authorized scp).

**Comment by JimKillock** [comment]
I think for now putting it on https://api.blocked.org.uk/data/export.csv.gz would make sense

The only privacy issue I would see is if the probe configs vary much - but even so, I’m not sure it matters much

**Comment by dantheta** [comment]
Deployed and configured.  I'll send an availability email to the techvols list too.
