### ISSUE TITLE
Output results per ISP / filter level

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#74]
display these on a page somewhere

**Comment by JimKillock** [comment]
Hoping it's ok to give you this task @dantheta!

**Comment by dantheta** [comment]
Yep, no worries!

**Comment by JimKillock** [comment]
I guess we should be interested in both default and maximal blocking levels, i.e. be able to return results for any of our _key_ probes. 

Not sure it should work like this for user probes tho. That would need to be cleverer, e.g. aggregate results by network provider, rather than probe.

**Comment by JimKillock** [comment]
Hey Dan, if you're able to do any of this before Thursday I'd be very grateful - we have a meeting with the over blocking working group then, so we can discuss the results :)

**Comment by dantheta** [comment]
I've prodded the database and made the BT-Strict, BT-Moderate and TalkTalk-Kidsafe results appear in the standard output.  Those entries are not being updated at the moment, but for any URL that exists in that recordset the historical results will be displayed with timestamps.

These appear on the static results page and the probe post-submission page.

The differing filter levels have been shoehorned into the existing response, so no frontend changes are necessary just yet.  It would be nice to enhance the JSON structure that comes from the API to make the filter level a structural part of the response.

**Comment by dantheta** [comment]
I've also added an API endpoint (/status/isp-stats) which shows a summary total for each URL stats (ok,blocked,error,timeout) by ISP/Filter Level.  If you did want a league table, or to produce an online version of the spreadsheet report, this API call will do it.  Docs appearing on the wiki shortly.

**Comment by JimKillock** [comment]
Fantastic, so @mkillock can write a front end filter? Looks like the stats html / java is easy enough to clone :)

**Comment by mkillock** [comment]
Having trouble with getting a response from this API at the moment - getting signature validation failure, can you help @dantheta

**Comment by dantheta** [comment]
Will be online shortly!

On 8 July 2014 21:09:31 GMT+01:00, mkillock notifications@github.com wrote:

> Having trouble with getting a response from this API at the moment -
> getting signature validation failure, can you help @dantheta 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/openrightsgroup/cmp-issues/issues/74#issuecomment-48393463

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dantheta** [comment]
This feature is now live at https://www.blocked.org.uk/isp-results

**Comment by graphiclunarkid** [comment]
Has anyone updated the FAQ with information about why some results appear not to update over time?
