### ISSUE TITLE
DMOZ / RDF import / export filter

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#76]
A filter to import DMOZ data, extract URL information, and then export it. The export could be manual, or via an API result (tagged in a similar way)

**Comment by dantheta** [comment]
I've temporarily paused the import, otherwise we'll run out of disk space on the database VM!

**Comment by graphiclunarkid** [comment]
I can increase the disk space available on the VM. Can you estimate how much is required?

**Comment by dantheta** [comment]
20GB would work, 40GB would be ideal.  That would allow us plenty of room for dmoz and the alex top 1m.  We can extend the VM or create a new database VM, either will work fine.

**Comment by graphiclunarkid** [comment]
I've increased the available disk-space to 45 GB of which about 35 GB is free right now.

**Comment by graphiclunarkid** [comment]
I think we've satisfied the basic requirement here so I'm going to close this issue. We should raise separate issues for integrating the very fine work you've all done into the front-end

Nice job :+1:
