### ISSUE TITLE
Check all UK charity websites using Blocked

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#82]
http://opencharities.org/ has the data we need … though it needs a bit of work to get the best impact. 

The dataset can be obtained here: http://OpenCharities.org/charities.csv.zip

The address with post code is contained in that dataset, along with the website address. Ideally, we would split this data into areas / cities etc, so that we could find good information for local stories. See for instance:

http://dundee.stv.tv/articles/282356-anger-as-isp-web-filters-block-access-to-fifty-scottish-charity-websites/?fromstreampost=141351

If we can split the data into regions, towns, or even constituencies, that’ll really help with campaigning.

The steps would be:
1. Clean the data and keep website and postcode
2. Use postcode look ups to group the websites / charities by region, constituency, town or locality
3. Run tests on each block to find likely mistakes
4. Hand check the websites (not all blocks are mistakes)
5. Do the press work!

**Comment by webal** [comment]
I've got a basic version of this working in a separate branch of the middleware (get_open_charities): https://github.com/openrightsgroup/Blocking-Middleware/blob/get_open_charities/backend/parse_open_charities.php

Currently it only adds in the url (and source), but at least we can use that to make sure all charities are getting checked. don't forget to add open_charities to urls.source column.

It would be useful to add in address (the data is there), I opened another issue to discuss how to start saving info about urls that are in multiple sources and fixing addresses in a standard format. Once we've figured out best way forward I'll go back and save this data with it.

THere's about 66000 unique urls within the file (quite a few dupes within the file itself)

**Comment by dantheta** [comment]
65237 URLs in the opencharities set.  Many thanks!

**Comment by JimKillock** [comment]
How difficult would it be to create some kind of visual tool like the DMOZ browser? Maybe based on the location data if that’s still attached?

**Comment by webal** [comment]
The address is all contained within a single field so it's a little hit and miss, but I would have thought we could get county & town fairly reliably. It does have postcode info as well, but this would be harder to fit into a search.

So if you're happy with county/town then shouldn't be too hard

**Comment by dantheta** [comment]
We've got some overlap between the opencharities data and the dmoz data too.  About 13,000 URLs from opencharities have got DMOZ categories.

**Comment by JimKillock** [comment]
Yes, you would hope there was some overlap :)

Browsing by [country or region?] » county » town would be great :)

**Comment by graphiclunarkid** [comment]
I think creating a "browse by location" feature is a separate issue so I'm closing this one in favour of #113. Thanks all!
