### ISSUE TITLE
Update Bytemark boilerplate on credits page

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#84]
The boilerplate for Bytemark on https://www.blocked.org.uk/credits is out of date. Updated copy below:

Bytemark Hosting has been the "geek hosting outfit of choice" for UK hosting since 2002, because it's run by a programmer (Matthew Bloch) and network engineer (Peter Taphouse) They have built it from scratch with a goal of technical excellence, writing most of their own software and tools to run the business exactly the way they want. With a staff of software engineers, they are continuing on that trajectory. Their hosting spans £10 per month servers to multi-site managed projects with high uptime guarantees.

Bytemark have two datacentres, in York and Manchester linked by a 10GBps national network, spanning London, Leeds and Scotland. This is overprovisioned compared to similarly-sized hosts, but with a goal of being robust in the face of random disconnections or abuse.

Bytemark run a comprehensive managed hosting service, and have host for big national brands like ASDA & Carling.com, government departments such as the Cabinet Office and the Department of Health, and hi-tech businesses such as Britain's largest mystery shopping company, Retail Eyes. They also have loan comparison companies, property search sites, car hire companies and thousands of smaller web developers who trust their clients to Bytemark's solid infrastructure and understanding of their software.

**Comment by graphiclunarkid** [comment]
Content updated. Review by Bytemark requested.

**Comment by technicalfault** [comment]
Looks fine by me - thanks!
