### ISSUE TITLE
Improve Open Graph / social media sharing metadata

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#85]
Comment from someone on LinkedIn after I shared the site homepage there: "You should rejig the introduction so that the first sentence of paragraph two appears in summaries like this one that's appeared on LinkedIn."

In general I think we need to review the open graph metadata tags to make sure they're presenting something coherent when our site is shared around the web.

**Comment by graphiclunarkid** [comment]
See also #55

**Comment by dantheta** [comment]
This is taken care of in the new frontend.
