### ISSUE TITLE
Do we want to accept probe responses against ISPs for which we have no blocking rules?

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/cmp-issues#88]
As a follow on from the discussion in #86, we're considering rejecting probe submissions from ISPs that aren't listed in the probe config file.  The suggested behaviour would be something like:
1. When a probe contacts the /status/ip endpoint to find out what ISP it's on, we provide an additional data item in the response telling the probe that responses won't be accepted.  Both the android probe and the python probe can then display information to the user telling them that the ISP is not one that is supported.  
2. If a probe still requests a URL to test against that ISP, they will be given a REST-style error response (invalid request or not found?), and some help text.
3. If a response is submitted for one of the ISPs, it will be met with an error code and some helpful text in the JSON response indicating that the submission has been rejected.

Advantages - 
- Saves on server resources.  At the moment, we instantiate a queue for every ISP that is returned in /status/ip (in preparation for a later request for a URL).  By limiting the range of ISPs that we hold in the system, we no longer have to expend memory/disk space on these queues.
- Dataset is cleaner.  The results dataset will no longer contain low numbers of results for wireless, mobile or fixed-line internet providers for which we have no rules.  All of these results are by definition "ok","error" or "timeout".  

Disadvantages -
- Someone using the android (or python) probe for the first time may be met with rejection notices based on their ISP.
- An earlier incarnation of the blocked project may have been pursuing censorship detection based on comparing responses from a known-clean line against those on an array of volunteer probes on unspecified networks (in much the same way that OONI does with Tor).  This restriction of ISP choices moves the project further away from this model.
- Having eliminated the submission of responses for unspecified ISPs, we lose the ability to run comparative analysis on the results from these (which might look for differences in HTTP status code, content length, etc).  I'm not sure that the response data we collect is rich enough for this at the moment anyway.
- The android probe may need updating with the newer user-visible behaviour, as might the python probe to a lesser extent.

Getting Involved - 
Another thing to include might be a pointer to the "get involved" pages.  If someone has a connection on an ISP that runs filtering, and we don't have config rules for it, where do we direct them in order to get rules set up for their ISP (probably orgtechvols or github issue)?. 

Perhaps this is the point that we introduce a separate app function that runs through a list of generally-good or generally-blocked sites (the canary list) to generate a set of block rules that can be submitted for addition to the probe config.

Any thoughts or preferences?  How should we proceed?

**Comment by dantheta** [comment]
I'm thinking that we should remove the queues for the untestable ISPs.  As we get rule information, we'll add them back.  Any other opinions?

**Comment by graphiclunarkid** [comment]
That sounds sensible to me.

**Comment by dantheta** [comment]
Code changes made, data and queues cleaned up.
