### ISSUE TITLE
Introduce sample data to the vagrant image, so that the API works "out-of-the-box"

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/cmp-issues#89]
This might include:
- A pre-registered user
- A pre-registered probe
- A pre-registered (fake) ISP
- A set of ISP cache entries that allow RFC1918 addresses to appear to match the fake ISP (since the ISP lookup is known to work poorly in this case)
- A dummy probe program, so that it is possible to end-to-end test the API inside vagrant

**Comment by dantheta** [comment]
We now have a demo user, probe and ISP set up in the vagrant database, automatically installed when the VM is first started.

OrgProbe also has a demo config file (config.vagrant.ini) which can be used to start OrgProbe running against a local vagrant VM.   

Hope this helps!

**Comment by dantheta** [comment]
Oops, didn't mean to stampede ahead.

Testing welcome on the Out-of-the-box experience.

**Comment by graphiclunarkid** [comment]
I'm not sure but I think we might have done this now. Is there anything left that we still want to do - or has the world moved on?

**Comment by dantheta** [comment]
I think it's there.  Cheers!
