### ISSUE TITLE
Respect robots.txt

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/cmp-issues#90]
Probes should respect robots.txt. For each for each resource (URL) under test we should first try to get robots.txt for that domain, and if it exists, we should handle any disallow conditions. We should not try to fetch resources for testing if robots.txt disallows access to them.
- If robots.txt doesn't exist then proceed to test the resource as normal.
- If robots.txt exists and permits us to fetch the resource then proceed to test as normal.
- If robots.txt exists and disallows access to the resource then record the result as "disallowed (robots.txt).
- If robots.txt is blocked, do we record the resource as blocked, or is that not a valid inference? Maybe we should have a new class of result for this e.g. "robots.txt was blocked"?

**Comment by dantheta** [comment]
I think that If robots.txt is blocked, we should go ahead and test the real URL anyway (there's virtually no chance that robots.txt would be blocked when the real resource isn't).

**Comment by dantheta** [comment]
In progress on OrgProbe.

**Comment by graphiclunarkid** [comment]
I can see how each probe ought to implement this, however if we ever end up vetting URLs before they are queued for probes to pick up, that might be a good point to fetch robots.txt and decide whether the URLs should be queued at all. We could do some clever caching here so that we don't have to fetch robots.txt every time a URL from a domain is submitted.

This would save some probe time and bandwidth but perhaps at the expense of increased pipeline latency.

**Comment by dantheta** [comment]
Yes, that does make sense - If we implement the robots.txt checking before sending the URL on to the network queues we'll save a lot of robots.txt requests from further on in the system.  With a warm robots.txt cache, we should be able to minimize any lag, and if we later implement an AJAX-style results page the extra delay will be compensated for there.  

We can also offload some robots.txt checking to the A&A VM (or any other clean line) if we find that we're creating a bottleneck on that part of the system.

If a URL was disallowed by robots.txt, how should we represent that in the results?  I think we could flag the URL as disallowed-by-robots, and then modify the /status/url response to indicate that it hasn't been tested on any ISPs for that reason.  Does that sound OK?

**Comment by graphiclunarkid** [comment]
That's pretty much exactly what I was thinking - down to the detail of compensating for increased latency with the AJAX-style results page and reporting the result as "disallowed" :smile:

**Comment by dantheta** [comment]
Cool - I'll scrap the probe branch and add it to the middleware.  All good!

**Comment by graphiclunarkid** [comment]
Did we ever finish this or is there something we still need to do?

**Comment by dantheta** [comment]
We've got a dormant branch which was waiting on ajax results.  I'll get it cleaned up and rebased, and then we can relaunch it.
