### ISSUE TITLE
Check Lato fonts work

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#93]
I didn't notice the alto had not been working (as I have it installed locally). I've amended the CSS to reference Lato fonts stored on the ORG server. Great of someone can check!

**Comment by graphiclunarkid** [comment]
I have the font installed too, but I checked using [this](http://www.atomicjetpacks.com/project/fontdetect/how-to-detect-if-a-font-really-loaded) and it seems to work correctly on the site.
