### ISSUE TITLE
Create frontend website page for email verification

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/cmp-issues#96]
Following on from #18, the API is now ready to accept email verification tokens.
A frontend webpage is needed to accept a token querystring argument and pass it to the API through the /verify/email endpoint, interpret the response and display an appropriate acknowledge to the user.

The /verify/email endpoint is described here: https://wiki.openrightsgroup.org/wiki/Censorship_Monitoring_Project_API#POST_.2Fverify.2Femail_.28proposed.29

**Comment by sr-murthy** [comment]
happy to work on this also.

**Comment by graphiclunarkid** [comment]
Hi @sr-murthy, I'm afraid this is another issue that isn't really suitable for newcomers, as we don't have a development server for our web front-end right now. That's the case with any issues labeled "modx" unfortunately.

**Comment by dantheta** [comment]
Added page at blocked.org.uk/confirm, linked from confirmation emails.
